### ISSUE TITLE
bamkit missing from 0.2.11 release

### ISSUE THREAD

**Issue by tk2** [arq5x/lumpy-sv#102]
Hi guys - I'm trying out lumpy, downloaded the v0.2.11 release tar ball, built it just fine but was getting this error when trying a test run:

can't open file '/nfs/compgen-02/user/tk2/1510-NGS-bioinf-sv/bin/lumpy-sv-0.2.11//scripts/bamkit/bamlibs.py': [Errno 2] No such file or directory

It seems that bamkit is missing from the release tar ball. I can work around this by getting all the dependencies by doing a clone with dependencies, but I wanted to use a tagged release version.

Thomas

**Comment by ryanlayer** [comment]
I fix this.  Thanks for letting me know.
