### ISSUE TITLE
bamkit still missing from Lumpy ZIP file

### ISSUE THREAD

**Issue by alig99** [arq5x/lumpy-sv#119]
Hi,
I downloaded the Lumpy ZIP file as git clone did not work for me.

The bamkit folder is empty so there are no bamlibs.py

Thank you

ali gardner

**Comment by cc2qe** [comment]
unfortunately github doesn't include recursive trees in the zipped releases. but you can download bamkit here: https://github.com/hall-lab/bamkit

**Comment by alig99** [comment]
Thank you so much for your rapid response.
________________________________

**Comment by ryanlayer** [comment]
The latest zip now includes bamkit.
