### ISSUE TITLE
Issue with lumpyexpress

### ISSUE THREAD

**Issue by adbeggs** [arq5x/lumpy-sv#121]
I'm having an issue getting lumpyexpress working on a BAM file I know is good. The only issue I can think of is that it has been aligned with Issac, Illumina's own aligner rather than BWA - do you think this is the problem rather than something else? I get a segmentation fault - see below:

### Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...
Warning: The index file is older than the data file: LP2000616-DNA_A01.bam.bai
samblaster: Version 0.1.22
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening LP2000616-DNA_A01.bam.vcf.nEj5wBNihpbT/disc_pipe for write.
sort: invalid option -- 'T'
samblaster: Opening LP2000616-DNA_A01.bam.vcf.nEj5wBNihpbT/spl_pipe for write.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
sort: invalid option -- 'T'
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Warning: The index file is older than the data file: LP2000616-DNA_A01.bam.bai
samblaster: Loaded 25 header sequence entries.
[samopen] SAM header is present: 25 sequences.
[samopen] SAM header is present: 25 sequences.
/usr/local/bin/lumpyexpress: line 268: 19069 Broken pipe             $SAMTOBAM $TEMP_DIR/disc_pipe
     19070 Segmentation fault      (core dumped) | $SAMSORT $TEMP_DIR/disc -o $TEMP_DIR/$OUTBASE.sample$(($i+1)).lib$(($j+1)).discordants.bam /dev/stdin
Traceback (most recent call last):
  File "/home/beggsa/lumpy-sv/scripts/bamkit/bamgroupreads.py", line 162, in <module>
[samopen] SAM header is present: 13 sequences.
    sys.exit(main())
  File "/home/beggsa/lumpy-sv/scripts/bamkit/bamgroupreads.py", line 158, in main
    bamgroupreads(args.input, args.readgroup, args.reset_dups, args.fix_flags, args.S, args.b, args.u)
  File "/home/beggsa/lumpy-sv/scripts/bamkit/bamgroupreads.py", line 91, in bamgroupreads
    [sam_read1] reference 'SN:13	LN:115169878	
R:/illumina/development/Isis/Genomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa	M5:51851ac0e1a115847ad36449b0015864
--stop-at Bam --lane-number-max 2048 --bam-header-tag @PG\tID:Illumina_WGS_Gel\tVN:v3.0.0 --reference-genome /illumina/development/Isis/Genomes/Homo_sapiens/Ensembl/GRCh37/Sequence/IsaacIndex/sorted-reference.xml --cleanup-intermediary 1 --memory-limit 122 --output-directory /scratch/LP2000616-DNA_A01_WF4951/Alignment/IsaacAlignment --temp-directory /scratch/LP2000616-DNA_A01_WF4951/Alignment/IsaacTemp --base-quality-cutoff 15 --stats-image-format none --variable-read-length yes --ignore-missing-bcls 1 --ignore-missing-filters 1 --per-tile-tls 1 --seed-length 32 -b /scratch/LP2000616-DNA_A01_WF4951/RunData/150420_HSQ9102_0344_AC5V3YANXX/RunInfo.xml --barcode-mismatches 1 --use-bases-mask Y125N1,Y125N1 --tiles s_4 --base-calls-format bcl-gz -s /scratch/LP2000616-DNA_A01_WF4951/Alignment/tmp.0.0.dat -b /scratch/LP2000616-DNA_A01_WF4951/RunData/150421_HSQ9102_0345_BC5V51ANXX/RunInfo.xml --barcode-mismatches 1 --use-bases-mask Y125N1,Y125N1 --tiles s_6,s_7,s_8 --base-calls-format bcl-gz -s /scratch/LP2000616-DNA_A01_WF4951/Alignment/tmp.1.0.dat -b /scratch/LP2000616-DNA_A01_WF4951/RunData/150422_HSQ9103_0378_AC5V2AANXX/RunInfo.xml --barcode-mismatches 1 --use-bases-mask Y125N1,Y125N1 --tiles s_1 --base-calls-format bcl-gz -s /scratch/LP2000616-DNA_A01_WF4951/Alignment/tmp.2.0.dat -b /scratch/LP2000616-DNA_A01_WF4951/RunData/150423_HSQ9103_0379_BC5V2FANXX/RunInfo.xml --barcode-mismatches 1 --use-bases-mask Y125N1,Y125N1 --tiles s_1 --base-calls-format bcl-gz -s /scratch/LP2000616-DNA_A01_WF4951/Alignment/tmp.3.0.dat	VN:iSAAC-01.14.02.06
' is recognized as '*'.
[main_samview] truncated file.
out_bam.write(al)
  File "pysam/calignmentfile.pyx", line 1287, in pysam.calignmentfile.AlignmentFile.write (pysam/calignmentfile.c:14502)
  File "pysam/calignmentfile.pyx", line 1316, in pysam.calignmentfile.AlignmentFile.write (pysam/calignmentfile.c:14424)
ValueError: sam write failed
beggsa@fuggle:/media/beggsa/data/genomes$ [sam_read1] reference '97' is recognized as '*'.

**Comment by cc2qe** [comment]
yeah it only works for BWA-MEM

https://github.com/arq5x/lumpy-sv#input
> "LUMPY Express expects BWA-MEM aligned BAM files as input."
