### ISSUE TITLE
lumpyexpress error with pathogen genome

### ISSUE THREAD

**Issue by madhubioinfo** [arq5x/lumpy-sv#153]
Hello
Am trying to run lumpy express on a pathogen genome of illumina dataset, and am running it with the genome and RNAseq file and it ran fine for producing bam file, am stuck where the vcf files are generated below is my command line
This is the warning message it shows when am running, and doesn't produce output file
**Checking for required python modules (/usr/bin/python)...
Warning: BAM file lacks read groups, paired-end analysis may fail
Calculating insert distributions...
done**

#bwa mem hti4.fa 141218_SND393_A_L005_HTI-1_trim_R1_filtered.fastq 141218_SND393_A_L005_HTI-1_trim_R2_filtered.fastq | samtools view -S -b  > sample.bam
#extract discordont paired-end alignments
#samtools view -b -F 1294 sample.bam > sample.discordants.unsorted.bam
#extract split read alignments
#samtools view -h sample.bam | /usr/ajeyadata/lumpy-sv/scripts/extractSplitReads_BwaMem -i stdin | samtools view -Sb  > sample.splitters.unsorted.bam
#sort both alignments
#samtools sort sample.discordants.unsorted.bam -o sample.discordants.bam
#samtools sort sample.splitters.unsorted.bam -o sample.splitters.bam
../../lumpy-sv/bin/lumpyexpress -B sample.bam -S sample.splitters.bam -D sample.discordants.bam -o sample.vcf

**Comment by cc2qe** [comment]
Does adding readgroups to your BAM file solve the problem?
https://github.com/ekg/bamaddrg

**Comment by madhubioinfo** [comment]
Hi,
am trying to clone this bamaddrg couldn't do it, are there any other program could do the same?

**Comment by cc2qe** [comment]
i think picard tools may be able to do it

___________________

**Comment by madhubioinfo** [comment]
yea thanks worked with picard tools well , i couldn't get the bedpe output format i got vcf
