### ISSUE TITLE
download incompletely

### ISSUE THREAD

**Issue by liufengxia99** [arq5x/lumpy-sv#154]
the  part “lumpof y-sv/scripts/bamkit” can't be downloaded simutaneously.  i sought the file's name maybe cause the problem(bamkit @ 148ef1d )

**Comment by cc2qe** [comment]
make sure you're running `git clone --recursive git@github.com:arq5x/lumpy-sv.git` to download the software. the `--recursive` flag ensures that bamkit is downloaded
