### ISSUE TITLE
Indel Relignment

### ISSUE THREAD

**Issue by jjfarrell** [arq5x/lumpy-sv#155]
Is indel realignment of the input bam recommended for Lumpy-SV?  Indel realignment has been dropped frrom the GATK best practices. Just wondering if it would be best to include indel realignment for preparing bams for Lumpy.

**Comment by cc2qe** [comment]
we do not use indel realignment as part of our SV calling pipeline. i suspect that it has a very minor effect, but have not tested it rigorously 

___________________
