### ISSUE TITLE
Prefered method of extracting split/discordant reads?

### ISSUE THREAD

**Issue by djakubosky** [arq5x/lumpy-sv#188]
Hi, 
I noticed a new package https://github.com/hall-lab/extract_sv_reads recently that appears to be for extracting split/discordant reads. Extracting split/discordants is done in a different way here, are the splitters/discordants identical between methods? Is there a preferred method to do this preprocessing?

Would appreciate any insights!

**Comment by ryanlayer** [comment]
The hall lab extract_sv_reads should work very well, but all of our methods are very similar.
