### ISSUE TITLE
Lumpyexpress output

### ISSUE THREAD

**Issue by 54tuifeimo** [arq5x/lumpy-sv#200]
I used the lumpyexpress with the  method recommended, and got the VCF file. Could you tell me the results is right? Why are the column of REF all N....？Thanks!

source /WORK/app/toolshs/cnmodule.sh
module load bcbio/0.9.9
lumpyexpress \
    -B SBM01_HW3N3CCXX_L3.recal_reads.bam \
    -S SBM01.splitters.bam \
    -D SBM01.discordants.bam \
    -o SBM01.vcf

Sourcing executables from /WORK/app/bcbio//bin/lumpyexpress.config ...

Checking for required python modules (/WORK/app/bcbio/anaconda/bin/python)...
Calculating insert distributions... 
Library read groups: SBM01_HW3N3CCXX_L3
Library read length: 150
Removed 372 outliers with isize >= 662
done
0
Running LUMPY... 
CM000812.5	1000000
CM000813.5	1000000
CM000814.5	1000000
CM000815.5	1000000
CM000816.5	1000000
CM000817.5	1000000
CM000818.5	1000000
CM000819.5	1000000
CM000820.5	1000000
CM000821.5	1000000
CM000822.5	1000000
CM000823.5	1000000
CM000824.5	1000000
CM000825.5	1000000
CM000826.5	1000000
CM000827.5	1000000
CM000828.5	1000000
CM000829.5	1000000
CM000830.5	1000000
LT634572.1	1000000
LUMPY Express done

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SBM01
CM000812.5      392679  1       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:15;SVLEN=-691;END=393370;CIPOS=-6,174;CIEND=-257,9;CIPOS95=0,49;CIEND95=-37,0;IMPRECISE;SU=15;PE=15;SR=0  GT:SU:PE:SR     ./.:15:15:0
CM000812.5      11      2_1     N       [CM000812.5:5438[N      .       .       SVTYPE=BND;STRANDS=--:66;EVENT=2;MATEID=2_2;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=66;PE=27;SR=39       GT:SU:PE:SR     ./.:66:27:39
CM000812.5      5438    2_2     N       [CM000812.5:11[N        .       .       SVTYPE=BND;STRANDS=--:66;SECONDARY;EVENT=2;MATEID=2_1;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=66;PE=27;SR=39     GT:SU:PE:SR     ./.:66:27:39
CM000812.5      119874  3       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:11;SVLEN=-52;END=119926;CIPOS=-3,2;CIEND=-3,2;CIPOS95=0,0;CIEND95=0,0;SU=11;PE=0;SR=11    GT:SU:PE:SR     ./.:11:0:11
CM000812.5      232455  4       N       <DUP>   .       .       SVTYPE=DUP;STRANDS=-+:10;SVLEN=249;END=232704;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-1,0;CIEND95=-1,1;IMPRECISE;SU=10;PE=6;SR=4       GT:SU:PE:SR     ./.:10:6:4
CM000812.5      234267  5       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-259;END=234526;CIPOS=-10,257;CIEND=-256,9;CIPOS95=-1,98;CIEND95=-70,2;IMPRECISE;SU=5;PE=5;SR=0   GT:SU:PE:SR     ./.:5:5:0
CM000812.5      277458  6       N       <DUP>   .       .       SVTYPE=DUP;STRANDS=-+:12;SVLEN=477;END=277935;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-3,0;CIEND95=-3,3;IMPRECISE;SU=12;PE=11;SR=1      GT:SU:PE:SR     ./.:12:11:1
CM000812.5      277868  7       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:23;SVLEN=-333;END=278201;CIPOS=-8,78;CIEND=-144,6;CIPOS95=-2,9;CIEND95=-41,2;IMPRECISE;SU=23;PE=23;SR=0   GT:SU:PE:SR     ./.:23:23:0
CM000812.5      392680  8       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-278;END=392958;CIPOS=-10,8;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;SU=5;PE=1;SR=4    GT:SU:PE:SR     ./.:5:1:4
CM000812.5      433966  9       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:9;SVLEN=-55;END=434021;CIPOS=-10,9;CIEND=-7,6;CIPOS95=0,0;CIEND95=0,0;SU=9;PE=4;SR=5      GT:SU:PE:SR     ./.:9:4:5
CM000812.5      456033  10      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:23;SVLEN=-79;END=456112;CIPOS=-10,9;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;SU=23;PE=0;SR=23  GT:SU:PE:SR     ./.:23:0:23
CM000812.5      456942  11      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-470;END=457412;CIPOS=-10,238;CIEND=-347,8;CIPOS95=-2,81;CIEND95=-115,0;IMPRECISE;SU=4;PE=4;SR=0  GT:SU:PE:SR     ./.:4:4:0
CM000812.5      471658  12      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-27;END=471685;CIPOS=-10,9;CIEND=-3,9;CIPOS95=0,0;CIEND95=0,1;IMPRECISE;SU=5;PE=0;SR=5    GT:SU:PE:SR     ./.:5:0:5
CM000812.5      492754  13      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:6;SVLEN=-2;END=492756;CIPOS=-5,0;CIEND=0,9;CIPOS95=0,1;CIEND95=0,0;IMPRECISE;SU=6;PE=0;SR=6       GT:SU:PE:SR     ./.:6:0:6
CM000812.5      498422  14      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-520;END=498942;CIPOS=-10,65;CIEND=-183,9;CIPOS95=-3,29;CIEND95=-47,3;IMPRECISE;SU=5;PE=5;SR=0    GT:SU:PE:SR     ./.:5:5:0
CM000812.5      499060  15      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-303;END=499363;CIPOS=-10,301;CIEND=-237,9;CIPOS95=-1,110;CIEND95=-60,2;IMPRECISE;SU=4;PE=4;SR=0  GT:SU:PE:SR     ./.:4:4:0
CM000812.5      557014  16      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-2982;END=559996;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-1,1;CIEND95=-1,1;IMPRECISE;SU=4;PE=2;SR=2       GT:SU:PE:SR     ./.:4:2:2
CM000812.5      224649  17_1    N       N]CM000812.5:604592]    .       .       SVTYPE=BND;STRANDS=++:6;EVENT=17;MATEID=17_2;CIPOS=-10,257;CIEND=-10,215;CIPOS95=-2,75;C

**Comment by 54tuifeimo** [comment]
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SBM01
CM000812.5      392679  1       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:15;SVLEN=-691;END=393370;CIPOS=-6,174;CIEND=-257,9;CIPOS95=0,49;CIEND95=-37,0;IMPRECISE;SU=15;PE=15;SR=0  GT:SU:PE:SR     ./.:15:15:0
CM000812.5      11      2_1     N       [CM000812.5:5438[N      .       .       SVTYPE=BND;STRANDS=--:66;EVENT=2;MATEID=2_2;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=66;PE=27;SR=39       GT:SU:PE:SR     ./.:66:27:39
CM000812.5      5438    2_2     N       [CM000812.5:11[N        .       .       SVTYPE=BND;STRANDS=--:66;SECONDARY;EVENT=2;MATEID=2_1;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=66;PE=27;SR=39     GT:SU:PE:SR     ./.:66:27:39
CM000812.5      119874  3       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:11;SVLEN=-52;END=119926;CIPOS=-3,2;CIEND=-3,2;CIPOS95=0,0;CIEND95=0,0;SU=11;PE=0;SR=11    GT:SU:PE:SR     ./.:11:0:11
CM000812.5      232455  4       N       <DUP>   .       .       SVTYPE=DUP;STRANDS=-+:10;SVLEN=249;END=232704;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-1,0;CIEND95=-1,1;IMPRECISE;SU=10;PE=6;SR=4       GT:SU:PE:SR     ./.:10:6:4
CM000812.5      234267  5       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-259;END=234526;CIPOS=-10,257;CIEND=-256,9;CIPOS95=-1,98;CIEND95=-70,2;IMPRECISE;SU=5;PE=5;SR=0   GT:SU:PE:SR     ./.:5:5:0
CM000812.5      277458  6       N       <DUP>   .       .       SVTYPE=DUP;STRANDS=-+:12;SVLEN=477;END=277935;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-3,0;CIEND95=-3,3;IMPRECISE;SU=12;PE=11;SR=1      GT:SU:PE:SR     ./.:12:11:1
CM000812.5      277868  7       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:23;SVLEN=-333;END=278201;CIPOS=-8,78;CIEND=-144,6;CIPOS95=-2,9;CIEND95=-41,2;IMPRECISE;SU=23;PE=23;SR=0   GT:SU:PE:SR     ./.:23:23:0
CM000812.5      392680  8       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-278;END=392958;CIPOS=-10,8;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;SU=5;PE=1;SR=4    GT:SU:PE:SR     ./.:5:1:4
CM000812.5      433966  9       N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:9;SVLEN=-55;END=434021;CIPOS=-10,9;CIEND=-7,6;CIPOS95=0,0;CIEND95=0,0;SU=9;PE=4;SR=5      GT:SU:PE:SR     ./.:9:4:5
CM000812.5      456033  10      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:23;SVLEN=-79;END=456112;CIPOS=-10,9;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;SU=23;PE=0;SR=23  GT:SU:PE:SR     ./.:23:0:23
CM000812.5      456942  11      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-470;END=457412;CIPOS=-10,238;CIEND=-347,8;CIPOS95=-2,81;CIEND95=-115,0;IMPRECISE;SU=4;PE=4;SR=0  GT:SU:PE:SR     ./.:4:4:0
CM000812.5      471658  12      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-27;END=471685;CIPOS=-10,9;CIEND=-3,9;CIPOS95=0,0;CIEND95=0,1;IMPRECISE;SU=5;PE=0;SR=5    GT:SU:PE:SR     ./.:5:0:5
CM000812.5      492754  13      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:6;SVLEN=-2;END=492756;CIPOS=-5,0;CIEND=0,9;CIPOS95=0,1;CIEND95=0,0;IMPRECISE;SU=6;PE=0;SR=6       GT:SU:PE:SR     ./.:6:0:6
CM000812.5      498422  14      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:5;SVLEN=-520;END=498942;CIPOS=-10,65;CIEND=-183,9;CIPOS95=-3,29;CIEND95=-47,3;IMPRECISE;SU=5;PE=5;SR=0    GT:SU:PE:SR     ./.:5:5:0
CM000812.5      499060  15      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-303;END=499363;CIPOS=-10,301;CIEND=-237,9;CIPOS95=-1,110;CIEND95=-60,2;IMPRECISE;SU=4;PE=4;SR=0  GT:SU:PE:SR     ./.:4:4:0
CM000812.5      557014  16      N       <DEL>   .       .       SVTYPE=DEL;STRANDS=+-:4;SVLEN=-2982;END=559996;CIPOS=-10,9;CIEND=-10,9;CIPOS95=-1,1;CIEND95=-1,1;IMPRECISE;SU=4;PE=2;SR=2       GT:SU:PE:SR     ./.:4:2:2
CM000812.5      224649  17_1    N       N]CM000812.5:604592]    .       .       SVTYPE=BND;STRANDS=++:6;EVENT=17;MATEID=17_2;CIPOS=-10,257;CIEND=-10,215;CIPOS95=-2,75;C:
`

**Comment by ryanlayer** [comment]
We set ref to N because some downstream tools error when ref is "." And the vcf would be very difficult to inspect if we put the full ref sequence for large deletions
