### ISSUE TITLE
Lumpy freezes, stops writing to output, no error

### ISSUE THREAD

**Issue by realsmicheletti** [arq5x/lumpy-sv#209]
I have had this issue running both traditional lumpy and lumpy express on RHEL 7.2

After a couple days of analysis, lumpy simply stops writing the vcf output. It gets through about half of the chromosomes then simply stops. Lumpy still appears to be running, and there is plenty of memory, but no advancement in the output files. 

It seems that the stopping point of lump is consistent when I try to re-run the program (in this case always at chromosome 12).  There is no error message. 

Is there any idea to why this is happening?

**Comment by ryanlayer** [comment]
Can you describe your experiment, give the command you ran, and exactly which chromosomes where scored?
