### ISSUE TITLE
No chromosomes defined in VCF header / sorting VCF output

### ISSUE THREAD

**Issue by colindaven** [arq5x/lumpy-sv#211]
Hi,

LUMPY runs through fine on my data which is nice.

However trying to sort the VCF is very problematic, so tabix fails.Therefore viz is difficult.

Specifically, `vt sort` complains that all CHROMS are missing from the VCF header. I believe the chromosomes should be defined according to the spec.

vcflib vcfstreamsort does sort, but tabix still complains.

Workarounds? 
cheers

**Comment by ryanlayer** [comment]
I use vcftoool sort and tabix often without issue. 

https://github.com/hall-lab/svtools

**Comment by colindaven** [comment]
Thanks for the comment. I see the chromosomes as headers are recommended but not required.

I'll look into the alternative tools you mentioned, and/or maybe mention this to the authors of vt.

http://samtools.github.io/hts-specs/VCFv4.1.pdf

"In addition, it is highly recommended (but not required) that the header include tags describing the reference
and contigs backing the data contained in the file. These tags are based on the SQ field from the SAM spec; all tags
are optional (see the VCF example above)."
