### ISSUE TITLE
Splitted bam files

### ISSUE THREAD

**Issue by woodoo46** [arq5x/lumpy-sv#213]
Hi Lumpy Developers,

I have a small question about the bam file. We already have alignment bam files splitted by chromosomes, for example, one human has 24 bam files. 

1) I am wondering if we can feed the data as is to Lumpy, meaning we do not need to combine the splitted bam files into one bigger bam file. 
2) Furthermore, can we use the splitted bam files for multiple samples calling?

Thanks.

George

**Comment by ryanlayer** [comment]
> On Oct 12, 2017, at 7:13 AM, woodoo46 <notifications@github.com> wrote:
> 
> Hi Lumpy Developers,
> 
> I have a small question about the bam file. We already have alignment bam files splitted by chromosomes, for example, one human has 24 bam files.
> 
> I am wondering if we can feed the data as is to Lumpy, meaning we do not need to combine the splitted bam files into one bigger bam file.

You can, but you will miss out of some translocation signal.
> Furthermore, can we use the splitted bam files for multiple samples calling?

Same as above. Make sure you keep the "id" field consistent across all your files for each sample.
