### ISSUE TITLE
Limiting calls to chr1-chr22,X,Y in GRCh38

### ISSUE THREAD

**Issue by jjfarrell** [arq5x/lumpy-sv#226]
The GRCh38 reference has 3367 contigs.  What is the best way to have lumpyexpress call variants only on chr1-chr22 and X and Y? 

A few approaches that seemed possible....
1. Adding all  the extra contigs to the exclude file. Is just the contig needed in the file or is it necessary to add the start and stop coordinates also? Is a certain sort order needed?
2. Use a reference with just chr1-chr22, X and Y. 
3. Or is there a way to specify the chromosomes to call in the command line?

**Comment by ryanlayer** [comment]
> On Jan 7, 2018, at 10:27 AM, jjfarrell <notifications@github.com> wrote:
> 
> The GRCh38 reference has 3367 contigs. What is the best way to have lumpyexpress call variants only on chr1-chr22 and X and Y?
> 
> A few approaches that seemed possible....
> 
> Adding all the extra contigs to the exclude file. Is just the contig needed in the file or is it necessary to add the start and stop coordinates also? Is a certain sort order needed?

This one is your best option.

Add "chrom 1 chrom_len" for each contig that you want to ignore.

They do not need to be sorted.

**Comment by jjfarrell** [comment]
Thanks! I will give that a try.
