### ISSUE TITLE
Can we use INFO SR PE for filtering?

### ISSUE THREAD

**Issue by ytguojian** [arq5x/lumpy-sv#231]
Hi Ryan,

In the final VCf file, can we use the term SR, PE or SU for filtering? If the average sequencing depth is about 20, what we should set? SU >20? or ...
Could you give me some suggestions on filtering?

Cheers,
Jian

**Comment by ryanlayer** [comment]
I would suggest genotyping your SVs with SVTYPER first, which will give you the alt and ref depths (AO and RO) considering a much lower quality threshold. THEN filter on AO for RO above some number. This will allow you to account for natural variability in coverage.

**Comment by ytguojian** [comment]
Yes. I have 357 samples which have been called variants using lumpyexpress and done genotyping with SVTyper separately already. So, there are 357 genotyped VCF files for me. Then I can filter them on AO or RO INFO separately. 
The problem I am facing is how to merge them. If I use the bcftools merge, there will be some closely but a little different variants. And It seems like that I do not use the merged VCF file getting from l_sort.py and l_merge.py.
So could you give me some suggestions? I just want to get one VCF file which contains the variants getting from  l_sort.py and l_merge.py ,and with genotyping information.

**Comment by ytguojian** [comment]
And another question. The function of the merged VCF file getting from l_sort.py and l_merge.py is to tell us how many variants we detect from 357 samples. Is that right?
Thanks.

**Comment by ytguojian** [comment]
Hi Ryan,
I think I have understood this protocal. To use the merged vcf file for sample genotyping separately, then I can get the sample genotyped variants. And These files can be merged by bcftools.
Thanks a lot.
Cheers,
Jian
