### ISSUE TITLE
SVTyper Best Practices for Lumpy Output

### ISSUE THREAD

**Issue by andrewSharo** [arq5x/lumpy-sv#248]
I was curious if there was an update on best practices for using SVTyper on the output from Lumpy. I tried the recommended command:
svtyper \      
    -B sample.bam \
    -S sample.splitters.bam \
    -i sample.vcf
    > sample.gt.vcf
but received an error message that the -S option has been deprecated. Is there another way I should be passing the split reads to SVTyper?

**Comment by ryanlayer** [comment]
Just use the sample bam

**Comment by andrewSharo** [comment]
Good to know, thanks.
