### ISSUE TITLE
Multiple calls in same region

### ISSUE THREAD

**Issue by rbalb** [arq5x/lumpy-sv#251]
Hi Ryan,

I had a question regarding lumpy calls - 

In my dataset, I managed to find a bunch of separate calls that overlap considerably.

For example (this is a subset of one sample, on the same chromosome):

chr start end length QUAL SVType
chr  11014836  11070622  55786   25.33    DUP 
chr  11015613  11070363  54750  119.60    DEL 
chr  11016535  11072796  56261  202.60    DUP 
chr  11017350  11072304  54954   47.58    DEL 
chr  11025022  11052632  27610   35.51    DUP 
chr  11026167  11052463  26296  203.70    DEL 
chr  11028884  11132399 103515   96.91    DUP 
chr  11029840  11061321  31481   27.17    DUP 

The vast majority of the variants also have the same genotype called using SVTyper.

I was wondering as to what causes this, how accurate these are, and the best practice for dealing with this situation (e.g. do I merge these variants into one/ by type etc.)?

Thanks,
Renzo

**Comment by ryanlayer** [comment]
Try visualizing that region with samplot. Could be a noisy region or complex SV.

https://github.com/ryanlayer/samplot

**Comment by rbalb** [comment]
Great, thanks - looks to be a complex SV.
