### ISSUE TITLE
Filter VCF Prior to Running SVTyper

### ISSUE THREAD

**Issue by andrewSharo** [arq5x/lumpy-sv#253]
Hi Ryan,
I'm getting a very large number of SVs in my vcf (~10^6) after running lumpyexpress on a single sample. SVTyper runs very slowly, so I'm looking to filter my vcf prior to running SVTyper. Do you recommend filtering by SU? Filtering for SU > 20 gives ~20,000 SVs which is more manageable. Do you think I may be losing a lot of real calls by doing this?  Should I focus instead on calls that have both split read and paired-end read support?

As a side note, do you think running lumpy jointly on multiple samples will help reduce the number of SVs per sample? I have about 100 samples, but have been running them individually.
Best, Andrew

**Comment by ryanlayer** [comment]
Human?

**Comment by andrewSharo** [comment]
Yes, human. I should have mentioned in the first post.

**Comment by ryanlayer** [comment]
Hg38?

**Comment by andrewSharo** [comment]
Yes, hg38.

**Comment by ryanlayer** [comment]
hg38 has _a_lot_ of contigs.

Try using this exclude file:

http://layerlabweb.s3.amazonaws.com/lumpy/hg38_lcr_rand.bed.gz

**Comment by ryanlayer** [comment]
I just updated this file, so you may need to redownload.

**Comment by andrewSharo** [comment]
Thanks, just downloaded. Will run and report back tomorrow.

**Comment by andrewSharo** [comment]
Hi Ryan,
Just ran with exclude file. I still ended up with 626,907 SVs, which is a lot less than 1M but still too much to all give to SVTyper. Let me know if you have any other ideas to decrease the number of SVs found by Lumpy. As I said in my first post, I'm considering filtering by SU or SU and SR since SR is potentially more reliable.

**Comment by ryanlayer** [comment]
How many are BNDs?

**Comment by andrewSharo** [comment]
Here's the approximate breakdown:
196,000 duplications
240,000 inversions
33,000 deletions
158,000 break ends

**Comment by ryanlayer** [comment]
What is your read depth?

**Comment by andrewSharo** [comment]
Sorry for the slow response. Depending on how it's calculated, read depth is 48 or 51.

**Comment by ryanlayer** [comment]
At that depth, I would require _at_ _least_ 7 reads. 10 is probably even
better.

**Comment by andrewSharo** [comment]
Great to know, and thanks for your help. So SU > 10. Should extra weight be given to calls with split read support?

**Comment by ryanlayer** [comment]
First off, many good calls will not have split read support and false positives can have support for both. But calls with multiple types of evidence are more convincing. The most convincing to me are those that also have coverage changes.

We are also starting to visualize most of our calls with samplot and SV-plaudit.

https://github.com/ryanlayer/samplot

https://github.com/jbelyeu/SV-plaudit

**Comment by andrewSharo** [comment]
Can I get coverage changes directly from the lumpy output vcf or would I need to look at the bams directly with the tools you recommend?  I see a BD INFO tag ("amount of bed evidence supporting the variant across all samples") but it seems none of the vcf entries actually have this tag.

**Comment by ryanlayer** [comment]
SVTYPER can report the depth. But you will need to run it first.

The BD tag is for when you include a bed file of read depth call from
something like CNVNator.

**Comment by andrewSharo** [comment]
Great, thank you.

**Comment by SunWinner01** [comment]
Hello, I am currently filtering the result files obtained from lumpy and svtyper. My raw sequencing data is 10x, and I first limited the length (50bp -1mb) and sv types (inv, del, dup). As an example of a sample file, I obtained 21659 lines of data initially. Afterwards, I plan to use support read for filtering. What is the appropriate threshold for SU that I set? However, I am still planning to filter based on QUAL in the end. Do you have any suggestions for setting these values? Looking forward to your reply! thank.
@ryanlayer
