### ISSUE TITLE
Missing ID for evidence of PE reads.

### ISSUE THREAD

**Issue by zhliUU** [arq5x/lumpy-sv#254]
Hi,

When printing the evidences for inversion with `-e`, I could see the IDs for split reads but not for paired-end reads. Is there any way to get the IDs of PE?
![wechatimg55](https://user-images.githubusercontent.com/36271531/42549279-f007ac94-84fd-11e8-9b16-e55a0f5c4d3a.png)

**Comment by ryanlayer** [comment]
You can use SVTYPER to get that info.

**Comment by zhliUU** [comment]
Maybe I wasn't clear about IDs I need.

I was looking for the reads name for the paired-end reads as shown in the second column for SR in the figured I uploaded. From SVTYPER I only got a bunch of statistic e.g GT:SU:PE:SR:GQ:SQ:GL:DP....
I will have to look into IGV if there is no convenient way to print them.

Thanks.

**Comment by ryanlayer** [comment]
Right. Sorry. You can pass an option to SVTYPER and it will create a bam of just the reads you want.
