### ISSUE TITLE
Is the last stable release from Lumpy from 2016?

### ISSUE THREAD

**Issue by evanbiederstedt** [arq5x/lumpy-sv#294]
I'm creating a Dockerfile for lumpy; there are several which already exist on Dockerhub. However, these are several years old. 

According to this: https://github.com/arq5x/lumpy-sv/releases
the last stable release is `v0.2.13` from March 30, 2016. However, this is an active repo with commits a few days ago. 

Should we be using this version as the latest stable version in the Dockerfile? Or is there a certain git commit you would recommend?

**Comment by ryanlayer** [comment]
I just made a new v0.3.0 release, please let me know how that goes.

**Comment by evanbiederstedt** [comment]
Thanks! We'll give it a spin
