### ISSUE TITLE
Cannot find gsl/gsl_rng.h

### ISSUE THREAD

**Issue by gerrybio** [arq5x/lumpy-sv#3]
Hi, I installed gsl package, and also modified the defs.local:
GSL_INCLUDE=-I/home/xxx/gsl-1.9/include/gsl/
# GSL_LINK=-L/sw/lib/

GSL_LINK=-L/home/xxx/gsl-1.9/lib/

I actually configured gsl package to some local directory.

Then I run "make" under lumpy package, then there's an error:
gsl-1.9/include/gsl/gsl_randist.h:22:25: error: gsl/gsl_rng.h: No such file or directory

I checked /include/gsl/ and definitely there exists gsl_rng.h file; it's very weird lumpy can find gsl_randist.h, but can't find gsl_rng.h, while these two files are under the same path.

I also added the path to PATH/LD_LIBRARY_PATH environmental, but still doesn't work.

I highly doubt there's a bug for defining pathways of gsl_rng.h

thanks!

**Comment by AngelCriollo** [comment]
Hi Ryan, I got the same problem when i tried to instal fineStructure (http://www.paintmychromosomes.com/) but I don't know how to edit the defs.local file. I guess is a file file from the program I'm trying to install, but I didn't find any similar file. Thank you so much.

**Comment by ryanlayer** [comment]
I am a little confused.  Are you using lumpy or does fineStructure use lumpy?

**Comment by AngelCriollo** [comment]
I'm trying to use fineStructure (not lumpy) and this is what I did:
./configure
make

and I got:

clang: warning: -lm: 'linker' input unused
clang: warning: -lz: 'linker' input unused
clang: warning: -lgsl: 'linker' input unused
clang: warning: -lgslcblas: 'linker' input unused
In file included from finestructure/state.cpp:3:
In file included from finestructure/state.h:3:
finestructure/rng.h:4:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>
         ^
1 error generated.
make[1]: *** [finestructure/fs-state.o] Error 1
make: *** [all] Error 2

I already installed gsl by using "brew instal gsl".
