### ISSUE TITLE
head instead of tail ?

### ISSUE THREAD

**Issue by lindenb** [arq5x/lumpy-sv#302]
related to https://github.com/arq5x/lumpy-sv/issues/235

in the recommandation: https://github.com/arq5x/lumpy-sv#lumpy-traditional , it is said:

```
samtools view -r readgroup1 sample.bam \
    | tail -n+100000 \
    | scripts/pairend_distro.py \
(...)
```

shouldn't it be  (`head` instead of `tail`) ?

```
samtools view -r readgroup1 sample.bam \
    | head -n 100000 \
    | scripts/pairend_distro.py \
(...)
```

**Comment by ryanlayer** [comment]
Since the BAMS are sorted, the beginning of a BAM contains reads from messy
areas of the chr1. We use tail to try and skip these.

**Comment by lindenb** [comment]
Ahh got it , thanks !
