### ISSUE TITLE
command not found for lumpyexpress

### ISSUE THREAD

**Issue by SaraAlthubaiti** [arq5x/lumpy-sv#311]
Hi team,

I have downloaded lumpy and try to use it, while running this command:
lumpyexpress \
    -B sample.bam \
    -S sample.splitters.bam \
    -D sample.discordants.bam \
    -o sample.vcf

I got this error:
-bash: lumpyexpress: command not found

Any help with that please?

**Comment by ryanlayer** [comment]
What steps did you take to download?

**Comment by SaraAlthubaiti** [comment]
That error has been sloved, Thanks
