### ISSUE TITLE
Lumpy specifies an inversion with two breakends only

### ISSUE THREAD

**Issue by jazberna1** [arq5x/lumpy-sv#325]
Hello,

I have run a tumour/nomal bam pair through Lumpy. There is one particular SV that Lumpy finds which could be a potential inversion as another tool (Delly) finds it too. However Lumpy does not produce the four records (breakends) that specify an inversion according to the vcf specifications (https://samtools.github.io/hts-specs/VCFv4.3.pdf). Instead, I only get two records in the vcf for such inversion. Is there a reason for that? I have pasted below the Lumy output for that variant as well as the Delly output.

Many thanks
Jorge

Lumpy: two records instead of four for an inversion
`16      52043343        3550_1  N       [16:52052737[N  23.68   .       SVTYPE=BND;STRANDS=--:7;IMPRECISE;CIPOS=-385,29;CIEND=-563,29;CIPOS95=-81,8;CIEND95=-140,5;MATEID=3550_2;E
VENT=3550;SU=7;PE=7;SR=0;AC=1;AN=2    GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:23:23.68:-11,-8,-39:53:46:6:46:6:0:0:0:46:6:0.12
16      52052737        3550_2  N       [16:52043343[N  23.68   .       SVTYPE=BND;STRANDS=--:7;IMPRECISE;CIPOS=-563,29;CIEND=-385,29;CIPOS95=-140,5;CIEND95=-81,8;MATEID=3550_1;E
VENT=3550;SECONDARY;SU=7;PE=7;SR=0;AC=1;AN=2  GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:23:23.68:-11,-8,-39:53:46:6:46:6:0:0:0:46:6:0.12`

Delly: one record that specify and inversion
`16	52043343	INV00008128	T	<INV>	.	PASS	IMPRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.7.9;CHR2=16;END=52052737;PE=7;MAPQ=43;CT=5to5;CIPOS=-346,346;CIEND=-346,346	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-16.7753,0,-221.751:10000:PASS:773:1365:704:2:42:7:0:0`

**Comment by ryanlayer** [comment]
Wow. The SV section of the VCF spec has been grant extended since we added our VCF output module. We do not follow this version of the spec, which would explain the difference. 

That said, I would be a bit suspicious of this INV because only negative strand pairs were observed (look at LUMPY’s STRAND field). The — and ++ pairs should roughly equal.

**Comment by jazberna1** [comment]
Hi,

Thanks so much! That was very clarifying.

Jorge
