### ISSUE TITLE
Can I get the copy number information?

### ISSUE THREAD

**Issue by hayeon-pak** [arq5x/lumpy-sv#375]
Hello,

I am trying to CNV analysis and going to make CNV plots.
So, I used lumpy and was able to get result of DEL, DUP, INV and etc using lumpyexpress and svtyper.
But I can't find copy number of DEL and DUP.
Can I get the copy number only from the <CNV> result? or which column is this?

Thank you.

**Comment by ryanlayer** [comment]
For DEL the copy number is reflected in the genotype 0/1 is one copy loss
and 1/1 is two copy loss. For DUP, we do something similar, but it is not
as straightforward. I would suggest running CNVnator on your samples to
estimate copy number.

**Comment by hayeon-pak** [comment]
Thank you for reply :)
I will refer to your answer.
