### ISSUE TITLE
lumpy-sv: both paired and split reads. Issue with bam file with split-reads.

### ISSUE THREAD

**Issue by dashainparis** [arq5x/lumpy-sv#41]
Hello, I've tried your tool for both paired and split reads. I took all the steps with extracting split-read, re-alignment and sorting reads with your scripts and it worked perfectly fine. But on the last step which corresponds directly to the lumpy I had the following error:

Could not open input BAM files: BamMultiReader::Open: unable to open inconsistent files:  
BamMultiReader::ValidateReaders: mismatched sort order in /Users/dasha/PhD/lumpy-sv/data/sim_soft.sort.bam, expected , but found coordinate.

Is that mean that the file was not sorted correct? I viewed the sim_soft.sort.bam in sam format and checked and it is seems to be sorted. To sort the file I used the commend that you recommend:

./samtools sort ~/PhD/lumpy-sv/data/sim_soft.bam sim_soft.sort

Do you have any recommendations?

Thank you in advance!

Daria

**Comment by donthu** [comment]
Hello,

I am also getting the same error. However, there are no empty lines in my file. 

@inti Could you resolve the issue?

**Comment by ryanlayer** [comment]
Are all of your files coordinate sorted?

On Thu, Jul 9, 2015 at 5:54 PM, donthu <notifications@github.com> wrote:

> Hello,
>
> I am also getting the same error. However, there are no empty lines in my
> file.
>
> @inti <https://github.com/inti> Could you resolve the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/41#issuecomment-120155731>.
>



-- 
Ryan Layer

**Comment by donthu** [comment]
Yes they are all coordinate sorted. In fact I did not get this error with one sample (Sample1) but I am getting with another sample (Sample2). I did not find any difference in the format for both the samples.

**Comment by ryanlayer** [comment]
can you send the two commands?  the one that works and the one that doesnt?

On Thu, Jul 9, 2015 at 5:58 PM, donthu <notifications@github.com> wrote:

> Yes they are all coordinate sorted. In fact I did not get this error with
> one sample (Sample1) but I am getting with another sample (Sample2). I did
> not find any difference in the format for both the samples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/41#issuecomment-120158238>.
>



-- 
Ryan Layer

**Comment by donthu** [comment]
The following command worked
```
$ lumpy     -mw 4     -tt 0     -pe id:Sample1,bam_file:Sample1.discordants.bam,histo_file:Sample1.histo,mean:458.06302521,stdev:78.8,read_length:250,min_non_overlap:250,discordant_z:5,back_distance:10,weight:1,min_mapping_threshold:20 -sr id:Sample1,bam_file:Sample1.splitters.bam,back_distance:10,weight:1,min_mapping_threshold:20 >Sample1_lumpy-sv.vcf
```
STDOUT:
```
531     0
gi|5XXXXXXXX|gb|XXXXXX.X|       1000000
```

The following command did NOT work

```
$ lumpy -mw 4 -tt 0 -pe id:Sample,bam_file:Sample2.bam,histo_file:Sample2.histo,mean:385.637091127,stdev:70.4,read_length:250,min_non_overlap:250,discordant_z:5,back_distance:10,weight:1,min_mapping_threshold:20 -sr id:Sample2,bam_file:Sample2.splitters2.bam,back_distance:10,weight:1,min_mapping_threshold:20 >Sample2_lumpy-sv.vcf
```
ERROR MESSAGE on std out:
```
423     0
Could not open input BAM files: BamMultiReader::Open: unable to open inconsistent files: 
BamMultiReader::ValidateReaders: mismatched sort order in Sample2_SL15.splitters2.bam, expected , but found coordinate
```

**Comment by donthu** [comment]
@ryanlayer 

Do you have any suggestions on this?

**Comment by donthu** [comment]
When I ran with discordants bam I did not get the error. My discordants bam was sorted.

**Comment by ryanlayer** [comment]
Can you check the headers of your BAM files?  Do they all state coordinate
sorted?

On Tue, Jul 14, 2015 at 10:54 AM, donthu <notifications@github.com> wrote:

> When I ran with discordants bam I did not get the error. My discordants
> bam was sorted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/41#issuecomment-121269535>.
>



-- 
Ryan Layer

**Comment by donthu** [comment]
Yes the problem was with unsorted BAM file. When I ran with sorted BAM the error is disappeared. Thank you for checking on this.

**Comment by ryanlayer** [comment]
Great!  Thanks.

On Tue, Jul 21, 2015 at 3:41 PM, donthu <notifications@github.com> wrote:

> Yes the problem was with unsorted BAM file. When I ran with sorted BAM the
> error is disappeared. Thank you for checking on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/41#issuecomment-123457359>.
>



-- 
Ryan Layer
