### ISSUE TITLE
Lumpy with mate-pair data

### ISSUE THREAD

**Issue by dashainparis** [arq5x/lumpy-sv#45]
Hello, I would like to use your tool on my mate-pair data, but I could not find any option in the list that will indicate it. Does lumpy work wiyh mate-pairs?

**Comment by osowiecki** [comment]
> Hi, we have never tested LUMPY on this data set. My hunch is that even if
> you correct for the read orientation, the large size and variation in
> fragment size will negatively effect the results. Sorry, Ryan
> 
> On Tue, Dec 9, 2014 at 6:43 AM, Dasha [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Hello, I would like to use your tool on my mate-pair data, but I could not
> > find any option in the list that will indicate it. Does lumpy work wiyh
> > mate-pairs?
> > —
> > Reply to this email directly or view it on GitHub
> > #45.
> 
> Ryan Layer

Seems like they did it and it works for some mate-pair data.

https://f1000research.com/articles/6-664#T3
