### ISSUE TITLE
Running with split reads and paired ends

### ISSUE THREAD

**Issue by amcpherson** [arq5x/lumpy-sv#49]
Running lumpy with paired ends:

    lumpy -mw 2 -tt 0.0 -pe discordant_z:4,weight:1,read_length:101,bam_file:tumour.bam,min_mapping_threshold:20,back_distance:20,histo_file:tumour.pe.histo,stdev:103.790551367,mean:286.228290332,id:1,min_non_overlap:101

I get:

    2110237	2110373	20	8097008	8097193	11	1.51668e-30	-	-	TYPE:INVERSION	IDS:1,12	STRANDS:--,12	MAX:20:2110353;20:8097193	95:20:2110297-2110357;20:8097193-8097193

Running with split reads from the same source data:

    lumpy -mw 2 -tt 0.0 -sr back_distance:20,bam_file:tumour.split.bam,min_mapping_threshold:20,id:2,weight:1

I get:

    2110319	2110360	20	8097150	8097192	8	0.00249794	-	-	TYPE:INVERSION	IDS:2,2	STRANDS:--,2	MAX:20:2110340;20:8097192	95:20:2110337-2110343;20:8097192-8097192

However, running with both together:

    lumpy -mw 2 -tt 0.0 -pe discordant_z:4,weight:1,read_length:101,bam_file:tumour.bam,min_mapping_threshold:20,back_distance:20,histo_file:tumour.pe.histo,stdev:103.790551367,mean:286.228290332,id:1,min_non_overlap:101 -sr back_distance:20,bam_file:tumour.split.bam,min_mapping_threshold:20,id:2,weight:1

Only the split reads are counted:

    20	2110319	2110360	20	8097150	8097192	9	0.00249794	-	-	TYPE:INVERSION	IDS:2,2	STRANDS:--,2	MAX:20:2110340;20:8097192	95:20:2110337-2110343;20:8097192-8097192

Is there any way to run lumpy in an integrated way and get it to report both split reads and paired ends for a prediction?

**Comment by ryanlayer** [comment]
This appears to be a bug.  Lumpy should be integrating the two signals.  Can you email me a slice of each bam file and your histo file so I can take a look?

**Comment by amcpherson** [comment]
I uploaded the full files to my dropbox here:

https://www.dropbox.com/sh/sjv9by5h6wmtr73/AAB4ocvi7of3BEu-8JbUTZDOa?dl=0

**Comment by bw2** [comment]
If I understand correctly that the 12 in `STRANDS:+-,12` represents the number of reads then I'm also seeing this bug in v0.2.9

**Comment by ryanlayer** [comment]
You need to sort your bams by coordinate order.  Once that is done these
two calls are merged:


20 2110341 18_1 N [20:8097172[N . .
SVTYPE=BND;STRANDS=--:14;EVENT=18;MATEID=18_2;CIPOS=-20,20;CIEND=-20,20;CIPOS95=-3,3;CIEND95=-3,2;IMPRECISE;SU=14;PE=12;SR=2
GT:SU:PE:SR ./.:12:12:0 ./.:2:0:2

NOTE: the newest version of lumpy prints VCF by default.  You can add the
"-b" option to get bedpe.  In which case the merged call is:

20 2110319 2110360 20 8097150 8097191 18 7.33379e-31 - - TYPE:INVERSION
IDS:1_PE,12;2_SR,2 STRANDS:--,14 MAX:20:2110340;20:8097171
95:20:2110337-2110343;20:8097168-8097173

On Wed, Mar 11, 2015 at 2:15 PM, bw2 <notifications@github.com> wrote:

> If I understand correctly that the 12 in STRANDS:+-,12 represents the
> number of reads then I'm also seeing this bug in v0.2.9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/49#issuecomment-78333680>.
>



-- 
Ryan Layer
