### ISSUE TITLE
pairend_distro.pl issue

### ISSUE THREAD

**Issue by mbourgey** [arq5x/lumpy-sv#53]
Hi, 
Previously I was using 0.2.2.3 but I switch to 0.2.9 in order to remove issue with the cigar string.
when I ran the 0.2.9 I get a new issue of memory leak which I determine (after reading issue posts) come from unrealistic estimate of mean and stdev. 

And effectively when runing the 0.2.9 version of pairend_distro.pl I get these estimates:
mean:69079.4060593941	stdev:2403723.04147885

whereas using  the version 0.2.2.3 I get for the same file:
mean:484.973802619738	stdev:15.7162627118735

for information my bam have been aligned using bwa-mem

For the moment I think I will use the 0.2.2.3 version of the script and the 0.2.9 version of lumpy

Thanks in advance

Mathieu

**Comment by cc2qe** [comment]
The perl version of pairend_distro is deprecated, do you get the same mean and stdev when running it on the python version? https://github.com/arq5x/lumpy-sv/blob/master/scripts/pairend_distro.py

**Comment by mbourgey** [comment]
using the python version I get:
mean:475.419231543      stdev:57.4334199847
which seems to be more realistic

thanks

**Comment by cc2qe** [comment]
@ryanlayer we might want to roll back this commit I made to the perl script (https://github.com/arq5x/lumpy-sv/commit/787af028b058b5097f949f026ecd8ed7aed1) because without requiring proper pairs, trimming values larger than 10 mads from the median is absolutely necessary.

or maybe just delete the perl script

**Comment by mbourgey** [comment]
Yes I will use the python version in my pipeline, perhaps a clearer indication that perl version is decrepated would be an asset or just remove it.

Thanks again

**Comment by ryanlayer** [comment]
Good idea.  PL version is gone.
