### ISSUE TITLE
Interpret the output bedpe file

### ISSUE THREAD

**Issue by blsfoxfox** [arq5x/lumpy-sv#54]
Hi Ryan,

I am working with catfish genome and just got the bedpe file from lumpy. However, some lines are bothering me. Could you please help me to interpret the result?

Following are part of the bedpe:

X	3093873	 3093897	X	15991008	15991032	3825	6.55015e-06	+	+	TYPE:INVERSION	IDS:2,6	STRANDS:++,6	MAX:X:3093886;X:15991021	95:X:3093885-3093887;X:15991020-15991022
X	1759864	1759888	X	15991631	15991655	3826	6.55015e-06	+	-	TYPE:DELETION	IDS:2,6	STRANDS:+-,6	MAX:X:1759877;X:15991644	95:X:1759876-1759878;X:15991643-15991645
X	14485949	14485986	X	15991702	15991739	3827	0.000127914	-	+	TYPE:DUPLICATION	IDS:2,4	STRANDS:-+,4	MAX:X:14485969;X:15991722	95:X:14485968-14485970;X:15991721-15991723
X	3093665	3093689	X	15991660	15991684	3828	6.55015e-06	-	-	TYPE:INVERSION	IDS:2,6	STRANDS:--,6	MAX:X:3093678;X:15991673	95:X:3093677-3093679;X:15991672-15991674
X	15727549	15727586	X	15993001	15993038	3829	0.000127914	+	+	TYPE:INVERSION	IDS:2,4	STRANDS:++,4	MAX:X:15727569;X:15993021	95:X:15727568-15727570;X:15993020-15993022
X	14185222	14185259	X	15993065	15993102	3830	0.000127914	+	+	TYPE:INVERSION	IDS:2,4	STRANDS:++,4	MAX:X:14185242;X:15993085	95:X:14185241-14185243;X:15993084-15993086
X	15993899	15993924	X	15993950	15993987	3831	0.000144119	+	+	TYPE:INVERSION	IDS:2,4	STRANDS:++,4	MAX:X:15993912;X:15993970	95:X:15993911-15993913;X:15993969-15993971

Does the first line mean there is a 12Mb inversion on Chromosome X between 3093873 and 15991032? If it is not ture, what can cause this? Mis-scaffolding?
You can see there are many inversions with similar right breakpoints at 15.9 Mb, but different left breakpoints. Could this be erroneous or common?

Thanks,

Bob

**Comment by ryanlayer** [comment]
Sorry this took me so long to get back to you on this.

What is the coverage of your sample, and what was the command you ran?

**Comment by blsfoxfox** [comment]
The coverage is 100X, and the command was 
lumpy -mw 4 -tt 0.0 -pe  bam_file:yype_abab_coco13_xxchromosome.discordant.pe.sort.bam,histo_file:yype_abab_coco13_xxchromosome.pe.histo,mean:7.12119085806,stdev:212.347788422,read_length:100,min_non_overlap:150,discordant_z:4,back_distance:20,weight:1,id:1,min_mapping_threshold:20 -sr bam_file:yype_abab_coco13_xxchromosome.sr.sort.bam,back_distance:20,weight:1,id:2,min_mapping_threshold:20 > yype_abab_coco13_chromosome.pesr.bedpe

The mean and stdev seems wrong to me, but it was generated by the pairend_distro.py script.

**Comment by ryanlayer** [comment]
Yes, the mean has got to be wrong.

Can you send me the first 100,000 lines of your bam file and your histo
file (ryan.layer AT gmail)

On Thu, Mar 19, 2015 at 11:20 AM, blsfoxfox <notifications@github.com>
wrote:

> The coverage is 100X, and the command was
> lumpy -mw 4 -tt 0.0 -pe
> bam_file:yype_abab_coco13_xxchromosome.discordant.pe.sort.bam,histo_file:yype_abab_coco13_xxchromosome.pe.histo,mean:7.12119085806,stdev:212.347788422,read_length:100,min_non_overlap:150,discordant_z:4,back_distance:20,weight:1,id:1,min_mapping_threshold:20
> -sr
> bam_file:yype_abab_coco13_xxchromosome.sr.sort.bam,back_distance:20,weight:1,id:2,min_mapping_threshold:20
> > yype_abab_coco13_chromosome.pesr.bedpe
>
> The mean and stdev seems wrong to me, but it was generated by the
> pairend_distro.py script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/54#issuecomment-83626243>.
>



-- 
Ryan Layer
