### ISSUE TITLE
lumpy error removing reads

### ISSUE THREAD

**Issue by mbourgey** [arq5x/lumpy-sv#56]
Hi 
when I was running lumpy v0.2.9 I get this error message:

Running  lumpy-sv 2015-01-29 13:38:26
466	0
491	0
chr10	1000000
chr10	2000000
chr10	4000000
chr11	1000000
chr11	2000000
chr11	4000000
chr12	1000000
chr12	2000000
chr12	4000000
chr13	1000000
chr13	2000000
chr13	4000000
chr14	1000000
chr14	2000000
chr14	4000000
chr15	1000000
chr15	2000000
chr15	4000000
chr16	1000000
chr16	2000000
chr16	4000000
chr17	1000000
chr17	2000000
chr17	4000000
chr18	1000000
chr18	2000000
chr18	4000000
chr19	1000000
chr19	2000000
chr19	4000000
chr1	1000000
chr1	2000000
chr1	4000000
chr2	1000000
chr2	2000000
chr2	4000000
chr3	1000000
chr3	2000000
chr3	4000000
chr4	1000000
chr4	2000000
chr4	4000000
chr5	1000000
chr5	2000000
chr5	4000000
chr6	1000000
chr6	2000000
chr6	4000000
Error removing element:chr6,91016653,91016653,+	chr6,91016674,91016674,-	1
./runLumpy.sh: line 38: 1906358 Aborted                 (core dumped) lumpy -mw 4 -tt 0.0 -pe bam_file:${TUMOR_PE},histo_file:${TUMOR_PE%.bam}.histo,mean:$tumorMean,stdev:$tumorStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:10,min_mapping_threshold:1 -pe bam_file:${BLOOD_PE},histo_file:${BLOOD_PE%.bam}.histo,mean:$bloodMean,stdev:$bloodStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:20,min_mapping_threshold:1 -sr bam_file:${TUMOR_SR},back_distance:20,weight:1,id:11,min_mapping_threshold:20 -sr bam_file:${BLOOD_SR},back_distance:20,weight:1,id:21,min_mapping_threshold:20 > $OUTPUT

It looks like what was discussed in the issue #33 but first you seems to have corrected this issue and second I don't see in any of the reads from the region a cigar string with no base matched.

do you have an idea ? do you want me to send you a slice of bams ?

thanks in advance

Mathieu

**Comment by mbourgey** [comment]
FYI, here is the list of all the cigar string from read mapped in the region surounding the problem (chr6:91016000-91018000) :
100M
12S88M
17S83M
22S75M
22S78M
28M24D72M
29S70M
30M1D25M34S
33M24D57M
36M24D64M
38M43H
38S43M
39M24D56M
39M54H
39M61H
39S54M
39S61M
44M56H
44S56M
45M51H
45S51M
46H36M
46M24D51M
46M24D54M
48M24D52M
49M34D50M
4S96M
51M34D43M
52M24D48M
55H34M
57H33M
57M33S
58M
62H38M
62M38S
64H32M
65H35M
67H33M
75M21S
76M24S
78M22S
83M
84M
87M13S
88M
92M
93M
94M
95M
97M
98M
99M

**Comment by ryanlayer** [comment]
Can you send me a slice that includes chr6:91014000-91018000 for all 4
bams, plus the two histo files associated with the two -pe?

On Tue, Feb 3, 2015 at 4:15 PM, mbourgey <notifications@github.com> wrote:

> FYI, here is the list of all the cigar string from read mapped in the
> region surounding the problem (chr6:91016000-91018000) :
> 100M
> 12S88M
> 17S83M
> 22S75M
> 22S78M
> 28M24D72M
> 29S70M
> 30M1D25M34S
> 33M24D57M
> 36M24D64M
> 38M43H
> 38S43M
> 39M24D56M
> 39M54H
> 39M61H
> 39S54M
> 39S61M
> 44M56H
> 44S56M
> 45M51H
> 45S51M
> 46H36M
> 46M24D51M
> 46M24D54M
> 48M24D52M
> 49M34D50M
> 4S96M
> 51M34D43M
> 52M24D48M
> 55H34M
> 57H33M
> 57M33S
> 58M
> 62H38M
> 62M38S
> 64H32M
> 65H35M
> 67H33M
> 75M21S
> 76M24S
> 78M22S
> 83M
> 84M
> 87M13S
> 88M
> 92M
> 93M
> 94M
> 95M
> 97M
> 98M
> 99M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-72736255>.
>



-- 
Ryan Layer

**Comment by mbourgey** [comment]
Hi ryan,

here is the link of a dropbox folder where you can find the slice of bam
surounding the region and the histo files:
https://www.dropbox.com/sh/bp1nrznbz4d2nxf/AAAMGSoD7KnmHef8lt3w6bX5a?dl=0

Thanks in advance

Mathieu 

Mathieu Bourgey, PhD
Chef d'équipe Production de Données et Services
Plateforme de bioinformatique
Centre d'innovation Génome Québec et Université McGill

**Comment by ryanlayer** [comment]
One last thing, the command you ran.

On Thu, Feb 5, 2015 at 3:15 PM, mbourgey <notifications@github.com> wrote:

> Hi ryan,
>
> here is the link of a dropbox folder where you can find the slice of bam
> surounding the region and the histo files:
> https://www.dropbox.com/sh/bp1nrznbz4d2nxf/AAAMGSoD7KnmHef8lt3w6bX5a?dl=0
>
> Thanks in advance
>
> Mathieu
>
> Mathieu Bourgey, PhD
> Chef d'équipe Production de Données et Services
> Plateforme de bioinformatique
> Centre d'innovation Génome Québec et Université McGill
>
>
> On 15-02-05 01:14 PM, Ryan Layer wrote:
> > Can you send me a slice that includes chr6:91014000-91018000 for all 4
> > bams, plus the two histo files associated with the two -pe?
> >
> > On Tue, Feb 3, 2015 at 4:15 PM, mbourgey <notifications@github.com>
> wrote:
> >
> >> FYI, here is the list of all the cigar string from read mapped in the
> >> region surounding the problem (chr6:91016000-91018000) :
> >> 100M
> >> 12S88M
> >> 17S83M
> >> 22S75M
> >> 22S78M
> >> 28M24D72M
> >> 29S70M
> >> 30M1D25M34S
> >> 33M24D57M
> >> 36M24D64M
> >> 38M43H
> >> 38S43M
> >> 39M24D56M
> >> 39M54H
> >> 39M61H
> >> 39S54M
> >> 39S61M
> >> 44M56H
> >> 44S56M
> >> 45M51H
> >> 45S51M
> >> 46H36M
> >> 46M24D51M
> >> 46M24D54M
> >> 48M24D52M
> >> 49M34D50M
> >> 4S96M
> >> 51M34D43M
> >> 52M24D48M
> >> 55H34M
> >> 57H33M
> >> 57M33S
> >> 58M
> >> 62H38M
> >> 62M38S
> >> 64H32M
> >> 65H35M
> >> 67H33M
> >> 75M21S
> >> 76M24S
> >> 78M22S
> >> 83M
> >> 84M
> >> 87M13S
> >> 88M
> >> 92M
> >> 93M
> >> 94M
> >> 95M
> >> 97M
> >> 98M
> >> 99M
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-72736255>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-73118317>.
>



-- 
Ryan Layer

**Comment by mbourgey** [comment]
Hi Ryan

here are the commands I ran for this pair.
FYI, I run the same commands for 11 other pairs without any issue.

Mathieu
commands:
###set-up PE

samtools view -h -F 0x0002 alignment/C107/C107.sorted.dup.recal.bam |
samtools view -S -h -F 0x0100 - | samtools view -h -S -F 0x0004 - |
samtools view -S -h -F 0x0008 - | samtools view -S -b -F 0x0400 - >
pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.tmp.bam && 
samtools sort  -@ 3 -m 1300M
pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.tmp.bam
pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted

samtools view -h -F 0x0002 alignment/T109/T109.sorted.dup.recal.bam |
samtools view -S -h -F 0x0100 - | samtools view -h -S -F 0x0004 - |
samtools view -S -h -F 0x0008 - | samtools view -S -b -F 0x0400 - >
pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.tmp.bam && 
samtools sort  -@ 3 -m 1300M
pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.tmp.bam
pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted


###set-up SR
samtools view -h alignment/C107/C107.sorted.dup.recal.bam | python
$LUMPY_SV_HOME/scripts/extractSplitReads_BwaMem -i stdin | samtools view
-Sb - > pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.tmp.bam && 
samtools sort  -@ 3 -m 1300M
pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.tmp.bam
pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted

samtools view -h alignment/T109/T109.sorted.dup.recal.bam | python
$LUMPY_SV_HOME/scripts/extractSplitReads_BwaMem -i stdin | samtools view
-Sb - > pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.tmp.bam && 
samtools sort  -@ 3 -m 1300M
pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.tmp.bam
pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted

###Lumpy-sv analysis

BLOOD=alignment/C107/C107.sorted.dup.recal.bam
TUMOR=alignment/T109/T109.sorted.dup.recal.bam
BLOOD_PE=pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.bam
TUMOR_PE=pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.bam
BLOOD_SR=pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.bam
TUMOR_SR=pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.bam
READ_LENGTH=100
OUTPUT=pairedVariants/WT1_C107_T109/lumpy/WT1_C107_T109.lumpy.bedpe

echo "Extracting iSize histograms " `date +"%Y-%m-%d %T"`
# Can't use pipefail because some pipes get closed too early by design
set +o pipefail
samtools view $BLOOD | tail -n+100000 | python
$LUMPY_SV_HOME/scripts/pairend_distro.py -r $READ_LENGTH -X 4 -N 10000
-o ${BLOOD_PE%.bam}.histo > ${BLOOD_PE%.bam}.histo.out
samtools view $TUMOR | tail -n+100000 | python
$LUMPY_SV_HOME/scripts/pairend_distro.py -r $READ_LENGTH -X 4 -N 10000
-o ${TUMOR_PE%.bam}.histo > ${TUMOR_PE%.bam}.histo.out
bloodDist=$(cat ${BLOOD_PE%.bam}.histo.out)
tumorDist=$(cat ${TUMOR_PE%.bam}.histo.out)

bloodMean=`echo $bloodDist | sed 's/mean:\([^ ]\+\) .*/\1/g'`
bloodStdev=`echo $bloodDist | sed 's/.* stdev:\([0-9.]\+\).*/\1/g'`

tumorMean=`echo $tumorDist | sed 's/mean:\([^ ]\+\) .*/\1/g'`
tumorStdev=`echo $tumorDist | sed 's/.* stdev:\([0-9.]\+\).*/\1/g'`

echo "Running  lumpy-sv" `date +"%Y-%m-%d %T"`
lumpy -mw 4 -tt 0.0 \
  -pe
bam_file:${TUMOR_PE},histo_file:${TUMOR_PE%.bam}.histo,mean:$tumorMean,stdev:$tumorStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:10,min_mapping_threshold:1\
  -pe
bam_file:${BLOOD_PE},histo_file:${BLOOD_PE%.bam}.histo,mean:$bloodMean,stdev:$bloodStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:20,min_mapping_threshold:1
\
  -sr
bam_file:${TUMOR_SR},back_distance:20,weight:1,id:11,min_mapping_threshold:20
\
  -sr
bam_file:${BLOOD_SR},back_distance:20,weight:1,id:21,min_mapping_threshold:20
\
  > $OUTPUT


Mathieu Bourgey, PhD
Chef d'équipe Production de Données et Services
Plateforme de bioinformatique
Centre d'innovation Génome Québec et Université McGill

**Comment by ryanlayer** [comment]
Since I don't have the full BAMs, I cannot determine the mean and stdev
values that are stored as variables here.  Can you please resent the lumpy
command with the actual values in place of the variables?  Thanks.

On Fri, Feb 6, 2015 at 12:41 PM, mbourgey <notifications@github.com> wrote:

> Hi Ryan
>
> here are the commands I ran for this pair.
> FYI, I run the same commands for 11 other pairs without any issue.
>
> Mathieu
> commands:
> ###set-up PE
>
> samtools view -h -F 0x0002 alignment/C107/C107.sorted.dup.recal.bam |
> samtools view -S -h -F 0x0100 - | samtools view -h -S -F 0x0004 - |
> samtools view -S -h -F 0x0008 - | samtools view -S -b -F 0x0400 - >
> pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.tmp.bam &&
> samtools sort -@ 3 -m 1300M
> pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.tmp.bam
> pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted
>
> samtools view -h -F 0x0002 alignment/T109/T109.sorted.dup.recal.bam |
> samtools view -S -h -F 0x0100 - | samtools view -h -S -F 0x0004 - |
> samtools view -S -h -F 0x0008 - | samtools view -S -b -F 0x0400 - >
> pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.tmp.bam &&
> samtools sort -@ 3 -m 1300M
> pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.tmp.bam
> pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted
>
>
> ###set-up SR
> samtools view -h alignment/C107/C107.sorted.dup.recal.bam | python
> $LUMPY_SV_HOME/scripts/extractSplitReads_BwaMem -i stdin | samtools view
> -Sb - > pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.tmp.bam &&
> samtools sort -@ 3 -m 1300M
> pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.tmp.bam
> pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted
>
> samtools view -h alignment/T109/T109.sorted.dup.recal.bam | python
> $LUMPY_SV_HOME/scripts/extractSplitReads_BwaMem -i stdin | samtools view
> -Sb - > pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.tmp.bam &&
> samtools sort -@ 3 -m 1300M
> pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.tmp.bam
> pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted
>
> ###Lumpy-sv analysis
>
> BLOOD=alignment/C107/C107.sorted.dup.recal.bam
> TUMOR=alignment/T109/T109.sorted.dup.recal.bam
> BLOOD_PE=pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.bam
> TUMOR_PE=pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.bam
> BLOOD_SR=pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.bam
> TUMOR_SR=pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.bam
> READ_LENGTH=100
> OUTPUT=pairedVariants/WT1_C107_T109/lumpy/WT1_C107_T109.lumpy.bedpe
>
> echo "Extracting iSize histograms " `date +"%Y-%m-%d %T"`
> # Can't use pipefail because some pipes get closed too early by design
> set +o pipefail
> samtools view $BLOOD | tail -n+100000 | python
> $LUMPY_SV_HOME/scripts/pairend_distro.py -r $READ_LENGTH -X 4 -N 10000
> -o ${BLOOD_PE%.bam}.histo > ${BLOOD_PE%.bam}.histo.out
> samtools view $TUMOR | tail -n+100000 | python
> $LUMPY_SV_HOME/scripts/pairend_distro.py -r $READ_LENGTH -X 4 -N 10000
> -o ${TUMOR_PE%.bam}.histo > ${TUMOR_PE%.bam}.histo.out
> bloodDist=$(cat ${BLOOD_PE%.bam}.histo.out)
> tumorDist=$(cat ${TUMOR_PE%.bam}.histo.out)
>
> bloodMean=`echo $bloodDist | sed 's/mean:\([^ ]\+\) .*/\1/g'`
> bloodStdev=`echo $bloodDist | sed 's/.* stdev:\([0-9.]\+\).*/\1/g'`
>
> tumorMean=`echo $tumorDist | sed 's/mean:\([^ ]\+\) .*/\1/g'`
> tumorStdev=`echo $tumorDist | sed 's/.* stdev:\([0-9.]\+\).*/\1/g'`
>
> echo "Running lumpy-sv" `date +"%Y-%m-%d %T"`
> lumpy -mw 4 -tt 0.0 \
> -pe
>
> bam_file:${TUMOR_PE},histo_file:${TUMOR_PE%.bam}.histo,mean:$tumorMean,stdev:$tumorStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:10,min_mapping_threshold:1\
> -pe
>
> bam_file:${BLOOD_PE},histo_file:${BLOOD_PE%.bam}.histo,mean:$bloodMean,stdev:$bloodStdev,read_length:$READ_LENGTH,min_non_overlap:$READ_LENGTH,discordant_z:4,back_distance:20,weight:1,id:20,min_mapping_threshold:1
> \
> -sr
>
> bam_file:${TUMOR_SR},back_distance:20,weight:1,id:11,min_mapping_threshold:20
> \
> -sr
>
> bam_file:${BLOOD_SR},back_distance:20,weight:1,id:21,min_mapping_threshold:20
> \
> > $OUTPUT
>
>
> Mathieu Bourgey, PhD
> Chef d'équipe Production de Données et Services
> Plateforme de bioinformatique
> Centre d'innovation Génome Québec et Université McGill
>
> On 15-02-06 11:07 AM, Ryan Layer wrote:
> > One last thing, the command you ran.
> >
> > On Thu, Feb 5, 2015 at 3:15 PM, mbourgey <notifications@github.com>
> wrote:
> >
> >> Hi ryan,
> >>
> >> here is the link of a dropbox folder where you can find the slice of bam
> >> surounding the region and the histo files:
> >>
> https://www.dropbox.com/sh/bp1nrznbz4d2nxf/AAAMGSoD7KnmHef8lt3w6bX5a?dl=0
> >>
> >> Thanks in advance
> >>
> >> Mathieu
> >>
> >> Mathieu Bourgey, PhD
> >> Chef d'équipe Production de Données et Services
> >> Plateforme de bioinformatique
> >> Centre d'innovation Génome Québec et Université McGill
> >>
> >>
> >> On 15-02-05 01:14 PM, Ryan Layer wrote:
> >>> Can you send me a slice that includes chr6:91014000-91018000 for all 4
> >>> bams, plus the two histo files associated with the two -pe?
> >>>
> >>> On Tue, Feb 3, 2015 at 4:15 PM, mbourgey <notifications@github.com>
> >> wrote:
> >>>> FYI, here is the list of all the cigar string from read mapped in the
> >>>> region surounding the problem (chr6:91016000-91018000) :
> >>>> 100M
> >>>> 12S88M
> >>>> 17S83M
> >>>> 22S75M
> >>>> 22S78M
> >>>> 28M24D72M
> >>>> 29S70M
> >>>> 30M1D25M34S
> >>>> 33M24D57M
> >>>> 36M24D64M
> >>>> 38M43H
> >>>> 38S43M
> >>>> 39M24D56M
> >>>> 39M54H
> >>>> 39M61H
> >>>> 39S54M
> >>>> 39S61M
> >>>> 44M56H
> >>>> 44S56M
> >>>> 45M51H
> >>>> 45S51M
> >>>> 46H36M
> >>>> 46M24D51M
> >>>> 46M24D54M
> >>>> 48M24D52M
> >>>> 49M34D50M
> >>>> 4S96M
> >>>> 51M34D43M
> >>>> 52M24D48M
> >>>> 55H34M
> >>>> 57H33M
> >>>> 57M33S
> >>>> 58M
> >>>> 62H38M
> >>>> 62M38S
> >>>> 64H32M
> >>>> 65H35M
> >>>> 67H33M
> >>>> 75M21S
> >>>> 76M24S
> >>>> 78M22S
> >>>> 83M
> >>>> 84M
> >>>> 87M13S
> >>>> 88M
> >>>> 92M
> >>>> 93M
> >>>> 94M
> >>>> 95M
> >>>> 97M
> >>>> 98M
> >>>> 99M
> >>>>
> >>>> —
> >>>> Reply to this email directly or view it on GitHub
> >>>> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-72736255>.
> >>>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-73118317>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-73280026>.
>



-- 
Ryan Layer

**Comment by mbourgey** [comment]
sorry about that !

here is the full commands:
lumpy -mw 4 -tt 0.0 -pe
bam_file:T109_subSample.discordant.pe.sorted.bam,histo_file:pairedVariants/WT1_C107_T109/lumpy/T109.discordant.pe.sorted.histo,mean:465.981455493,stdev:38.3231228518,read_length:100,min_non_overlap:100,discordant_z:4,back_distance:20,weight:1,id:10,min_mapping_threshold:1
-pe
bam_file:pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.bam,histo_file:pairedVariants/WT1_C107_T109/lumpy/C107.discordant.pe.sorted.histo,mean:475.419231543,stdev:57.4334199847,read_length:100,min_non_overlap:100,discordant_z:4,back_distance:20,weight:1,id:20,min_mapping_threshold:1
-sr
bam_file:pairedVariants/WT1_C107_T109/lumpy/T109.sr.sorted.bam,back_distance:20,weight:1,id:11,min_mapping_threshold:20
-sr
bam_file:pairedVariants/WT1_C107_T109/lumpy/C107.sr.sorted.bam,back_distance:20,weight:1,id:21,min_mapping_threshold:20
> pairedVariants/WT1_C107_T109/lumpy/WT1_C107_T109.lumpy.bedpe

Mathieu

Mathieu Bourgey, PhD
Chef d'équipe Production de Données et Services
Plateforme de bioinformatique
Centre d'innovation Génome Québec et Université McGill

**Comment by mbourgey** [comment]
Hi Ryan,
I just noticed that you requested the slices of bam for the region:
chr6:91014000-91018000
and that I gave you thoses for the region :
chr6:91016000-91018000

do you want me to upload the slices of the region  chr6:91014000-91018000 ?

Thanks

Mathieu

**Comment by ryanlayer** [comment]
Nope.  The slices you gave me reproduce the error.  Thanks.

On Tue, Feb 10, 2015 at 4:33 PM, mbourgey <notifications@github.com> wrote:

> Hi Ryan,
> I just noticed that you requested the slices of bam for the region:
> chr6:91014000-91018000
> and that I gave you thoses for the region :
> chr6:91016000-91018000
>
> do you want me to upload the slices of the region chr6:91014000-91018000 ?
>
> Thanks
>
> Mathieu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-73788329>.
>



-- 
Ryan Layer

**Comment by ryanlayer** [comment]
The issues is with this pair:

FCC4MAYACXX:6:1112:8359:93218# 97 chr6 91016551 49 52M24D48M = 91016654 236
FCC4MAYACXX:6:1112:8359:93218# 145 chr6 91016654 40 49M34D50M = 91016551
-236

The CIGAR string makes the read appear to be 124 bases (up to 91016675),
which overlaps with the other end.  We typically ignore these overlaps by
setting the "min_non_overlap" parameter to the read length (100).  HOWEVER
in this case the breakpoint is considered because the non overlap is 103
(>100), but the reads still overlap b/c the apparent read length is 124.
After this point things get messy and result in the error you see.

There are a few ways to fix this, but I am not sure the best yet.  I will
get back to you soon.



On Thu, Feb 12, 2015 at 11:25 AM, Ryan Layer <ryan.layer@gmail.com> wrote:

> Nope.  The slices you gave me reproduce the error.  Thanks.
>
> On Tue, Feb 10, 2015 at 4:33 PM, mbourgey <notifications@github.com>
> wrote:
>
>> Hi Ryan,
>> I just noticed that you requested the slices of bam for the region:
>> chr6:91014000-91018000
>> and that I gave you thoses for the region :
>> chr6:91016000-91018000
>>
>> do you want me to upload the slices of the region chr6:91014000-91018000 ?
>>
>> Thanks
>>
>> Mathieu
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/arq5x/lumpy-sv/issues/56#issuecomment-73788329>.
>>
>
>
>
> --
> Ryan Layer
>



-- 
Ryan Layer

**Comment by mbourgey** [comment]
why the cigar D value is count in the read length ? it reports a deletion so it corresponds to reference bases not reads bases ?
Perhaps I miss something there.

my 2c

Mathieu

**Comment by ryanlayer** [comment]
I think my inclusion of read length confused things here.  The D in the cigar resulted in the right-most mapped sequence of the left end to be greater than the left-most mapped sequence of the right end.  Basically, the two ends overlap.  This breaks a base assumption in LUMPY.  I have fixed the code so that these cases do not cause LUMPY to fail.

**Comment by calkan** [comment]
Hi @ryanlayer , reopening this. I have the same problem
(v 0.2.11)

lumpyexpress -B HG00096.recal.bam -o HG00096.vcf

BAM file:

http://alkanlab.org/share/lumpy/
