### ISSUE TITLE
Not sure if it's working properly

### ISSUE THREAD

**Issue by ediezben** [arq5x/lumpy-sv#63]
Ran the following:

git clone git://github.com/arq5x/lumpy-sv.git
cd lumpy-sv
make
wget http://www.cs.virginia.edu/~rl6sf/lumpy/data.tar.gz
tar -xzvf data.tar.gz
cd test
./test.sh

And I got this output:

Testing lumpy paired-end
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:71	True:0	False:1
Testing lumpy split-read
chr10	1000000
Simulated:1000	Predicted:75	True:0	False:1
Testing lumpy paired-end and split-read
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:307	True:0	False:1

Is it right? because the results in the README for the test are different and in my results none of the predicted SV are marked as true. I am afraid there's something not working and it cannot spot the error because I am planning to run the software on a quite big dataset. Does that mean I have something missing/non-installed? It did not throw any error though.

**Comment by ryanlayer** [comment]
The BAMs in the test did not have the correct headers.  I updated the URL for the test data.  Please try that new file.
