### ISSUE TITLE
test.sh True:0

### ISSUE THREAD

**Issue by wb223495** [arq5x/lumpy-sv#64]
I installed lumpy and when I run the test.sh script it seems to work but the values I get for true is always zero, however shouldn't they be close to the predicted values? Please advise!

I get the following output:

Testing lumpy paired-end
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:71	True:0	False:1
Testing lumpy split-read
chr10	1000000
Simulated:1000	Predicted:75	True:0	False:1
Testing lumpy paired-end and split-read
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:307	True:0	False:1

**Comment by ryanlayer** [comment]
Please try the new test data set at http://layerlab.org/lumpy/data.tar.gz

On Thu, Apr 2, 2015 at 1:26 PM, wb223495 <notifications@github.com> wrote:

> I installed lumpy and when I run the test.sh script it seems to work but
> the values I get for true is always zero, however shouldn't they be close
> to the predicted values? Please advise!
>
> I get the following output:
>
> Testing lumpy paired-end
> Removed 12 outliers with isize >= 850
> 549 0
> chr10 1000000
> Simulated:1000 Predicted:71 True:0 False:1
> Testing lumpy split-read
> chr10 1000000
> Simulated:1000 Predicted:75 True:0 False:1
> Testing lumpy paired-end and split-read
> Removed 12 outliers with isize >= 850
> 549 0
> chr10 1000000
> Simulated:1000 Predicted:307 True:0 False:1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/64>.
>



-- 
Ryan Layer

**Comment by wb223495** [comment]
I downloaded the data and I tried again with the same result:

Testing lumpy paired-end
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:71	True:0	False:1
Testing lumpy split-read
chr10	1000000
Simulated:1000	Predicted:75	True:0	False:1
Testing lumpy paired-end and split-read
Removed 12 outliers with isize >= 850
549	0
chr10	1000000
Simulated:1000	Predicted:307	True:0	False:1

**Comment by ryanlayer** [comment]
LUMPY not emits VCF by default.  This test assumed BEDPE output.  The test scripts have fixed.  Everything should now work.
