### ISSUE TITLE
Support for 'supplementary alignment' bam flag?

### ISSUE THREAD

**Issue by galaxyrise** [arq5x/lumpy-sv#67]
Sorry, this is more of a feature request than 'Issue' report.  I read your paper with great interest and was hoping to try LUMPY on my dataset, but noted in your instructions that you require that bwa-mem utilize the legacy '-M' flag.  My data were not generated using this flag, and it probably isn't feasible for me to reprocess all my samples.  This leads me to my question: Do you have any plans to add support for the 'supplementary alignment' flag?

As background for anyone else reading this who may be unaware, the '-M' flag was added to bwa-mem for backward compatibility since the 'supplementary alignment' flag was a more recent addition to the bam spec and was not originally supported by older tools.  (The primary issue was incompatibility with picard's mark duplicates functionality, but picard added support over a year ago; see also: https://www.biostars.org/p/97323/.)

Thanks!

**Comment by ryanlayer** [comment]
Thank you for brining this to our attention.  We no longer require the "-M" option in bwa mem alignments.

**Comment by galaxyrise** [comment]
Just got back from vacation and was happy to see your response.  Will give
Lumpy a test drive today.  Thanks for your help!

Regards,
Oliver

**Comment by nswh** [comment]
we tried with and without -M option in alignment. However we got a large discrepancy of the results of Lumpy calls which are 1552 with -M and 3130 without -M. Any explanations?

**Comment by ryanlayer** [comment]
-M changes the flags to be compatible with other software. Omitting -M sets flags correctly and give the best results.
