### ISSUE TITLE
No bamfile with discordants

### ISSUE THREAD

**Issue by ksahlin** [arq5x/lumpy-sv#69]
Hi,
I issued the following command

     lumpyexpress -B mapped.bam

and got the following:

"Sourcing executables from /proj/b2013072/private/svest_evaluation/tools_bin/lumpyexpress.config ...

Checking for required python modules (/home/kris/.pyenv/shims/python)...
mv: cannot stat `mapped.bam.vcf.W2ojEnfUwn7C/mapped.bam.vcf.sample1.lib1.discordants.bam': No such file or directory"

Could this be because no reads were detected as discordant?

I also wanted to check that the bam file was sorted 

     python ../tools_src/lumpy-sv/scripts/check_sorting.py ../data/100_200_deletions/mapped.bam ../data/100_200_deletions/mapped.bam

and got
"Traceback (most recent call last):
  File "../tools_src/lumpy-sv/scripts/check_sorting.py", line 47, in <module>
    if order.index(chrom) > curr_chrom_index:
ValueError: '*' is not in list"

**Comment by leejianfeng** [comment]
You need conduct some pre-processing on your mapped.bam file,such as the speedseq(https://github.com/cc2qe/speedseq)  or  BWA-MEM.

**Comment by ryanlayer** [comment]
The error with check_sorting would seem to indicate that the first record
in your bam file is an unaligned read.  Which would seem to indicate that
you have an unsorted bam.  Please sort and try again.  I am going to add an
issue to fix the check_sorting script to handle this case.

On Thu, Apr 9, 2015 at 11:38 AM, Kristoffer <notifications@github.com>
wrote:

> Hi,
> I issued the following command
>
>  lumpyexpress -B mapped.bam
>
> and got the following:
>
> "Sourcing executables from
> /proj/b2013072/private/svest_evaluation/tools_bin/lumpyexpress.config ...
>
> Checking for required python modules (/home/kris/.pyenv/shims/python)...
> mv: cannot stat
> `mapped.bam.vcf.W2ojEnfUwn7C/mapped.bam.vcf.sample1.lib1.discordants.bam':
> No such file or directory"
>
> Could this be because no reads were detected as discordant?
>
> I also wanted to check that the bam file was sorted
>
>  python ../tools_src/lumpy-sv/scripts/check_sorting.py ../data/100_200_deletions/mapped.bam ../data/100_200_deletions/mapped.bam
>
> and got
> "Traceback (most recent call last):
> File "../tools_src/lumpy-sv/scripts/check_sorting.py", line 47, in
> if order.index(chrom) > curr_chrom_index:
> ValueError: '*' is not in list"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/69>.
>



-- 
Ryan Layer
