### ISSUE TITLE
Error: BAM files must be coordinate sorted

### ISSUE THREAD

**Issue by gaoyan07** [arq5x/lumpy-sv#70]
Hi,
I got the "Error: BAM files must be coordinate sorted" when executing lumpy-sv with a sorted bam file.
I have already cheched the bam file with the "check_sorting.py", and the result is "in order".

    $ python ../scripts/check_sorting.py test.sam_sort.bam
    test.sam_sort.bam
    in order
    $ ./lumpy -mw 4 -tt 0 -sr id:mol1,bam_file:test.sam_sort.bam,back_distance:10,weight:1,min_mapping_threshold:20
    Error: BAM files must be coordinate sorted

Looking forward to any replies.
Thanks very much!

**Comment by ryanlayer** [comment]
Can you paste in the header to your bam?

**Comment by gaoyan07** [comment]
The header:

$ samtools view -h test.sam_sort.bam

    @SQ     SN:chr1 LN:249250621
    @SQ     SN:chr2 LN:243199373
    @SQ     SN:chr3 LN:198022430
    @SQ     SN:chr4 LN:191154276
    @SQ     SN:chr5 LN:180915260 
    @SQ     SN:chr6 LN:171115067 
    @SQ     SN:chr7 LN:159138663
    @SQ     SN:chr8 LN:146364022
    @SQ     SN:chr9 LN:141213431
    @SQ     SN:chr10        LN:135534747
    @SQ     SN:chr11        LN:135006516
    @SQ     SN:chr12        LN:133851895
    @SQ     SN:chr13        LN:115169878
    @SQ     SN:chr14        LN:107349540
    @SQ     SN:chr15        LN:102531392
    @SQ     SN:chr16        LN:90354753
    @SQ     SN:chr17        LN:81195210
    @SQ     SN:chr18        LN:78077248
    @SQ     SN:chr19        LN:59128983
    @SQ     SN:chr20        LN:63025520
    @SQ     SN:chr21        LN:48129895
    @SQ     SN:chr22        LN:51304566
    @SQ     SN:chrX LN:155270560
    @SQ     SN:chrY LN:59373566
    @PG     ID:bwa  PN:bwa  VN:0.7.12-r1039 CL:./bwa mem -B3 -O5 -E2 /home/gaoyan/Data/hg19/whole/hg19.fa /data/gaoyan/illmina_long/mol1/mol1.fa

**Comment by cc2qe** [comment]
LUMPY is looking for an HD tag in your header that specifies the sorting
```
@HD	VN:1.3	SO:coordinate
```

If your BAM is coordinate sorted, you can add this line to the top of the header and it should work. Normally it is automatically added by the sorting software.

**Comment by gaoyan07** [comment]
Thanks, cc2qe.
It works!!!
