### ISSUE TITLE
Merging VCFs output by lumpy express.

### ISSUE THREAD

**Issue by smilefreak** [arq5x/lumpy-sv#71]
Hi,

I have been trying to merge the VCFs output from lumpyexpress. 

But I get the following error in l_merge.py

I realise this is because the PRPOS is missing from the info line of VCF file output by lumpy.

```
File "/Volumes/BiochemXsan/scratch/merrimanlab/james/CNV_exomes/lumpy-sv/scripts/l_bp.py", line 147, in __init__
    self.p_l = [float(x) for x in m['PRPOS'].split(',')]
```

Does anyone have a solution to this problem?

Thanks.

**Comment by cc2qe** [comment]
l_merge needs the probability curve in the VCF file. Use the -P flag to output this field

**Comment by smilefreak** [comment]
Great thanks.
