### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by RobinvanVelzen** [arq5x/lumpy-sv#74]
Hi 

I installed lumpy and the test/test.sh  rusn fine. However, when running lumpyexpress on my own data I get a directory error:

```
$ ~/progs_nobackup/lumpy-sv-master/bin/lumpyexpress -B /mnt/nexenta/bwa_PriWU20x00_PanWU01x14_asm01/bwa_PriWU20x00-PanWU01x14_asm01_sorted.bam -o bwa_PriWU20x00-PanWU01x14_asm01_sorted.vcf -k -v
Sourcing executables from /home/velze002/progs_nobackup/lumpy-sv-master/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...

    create temporary directory
mv: cannot stat 'bwa_PriWU20x00-PanWU01x14_asm01_sorted.vcf.NbwNNtv0WQ27/bwa_PriWU20x00-PanWU01x14_asm01_sorted.vcf.sample1.lib1.discordants.bam': No such file or directory
$ ls -l
total 5
drwx------+ 4 velze002 velze002   6 Apr 28 16:00 bwa_PriWU20x00-PanWU01x14_asm01_sorted.vcf.NbwNNtv0WQ27
$ ls -l bwa_PriWU20x00-PanWU01x14_asm01_sorted.vcf.NbwNNtv0WQ27/
total 7
drwxrwxr-x  2 velze002 velze002 2 Apr 28 16:00 disc
prw-rw-r--+ 1 velze002 velze002 0 Apr 28 16:00 disc_pipe
drwxrwxr-x  2 velze002 velze002 2 Apr 28 16:00 spl
prw-rw-r--+ 1 velze002 velze002 0 Apr 28 16:00 spl_pipe
```
It seems that lumpyexpress expects a discordants.bam file that does not exist. However, I did not specify any discordants file in the input and I don't think lumpy had tried computing one yet. 

The bam alignment was created with bwa mem and sorted using samtools. 

Does anyone know what may be going wrong: Maybe there is an issue with samblaster ? 

Thanks in advance for any help!

**Comment by cc2qe** [comment]
Several people have been having problems running lumpyexpress without discordants/splitters BAM files. When you only supply a BAM, lumpyexpress attempts to automatically generate the discordants/splitters files with SAMBLASTER, but there are apparently some issues that I'll try to fix.

In the meantime, it may be easiest to run the [pre-processing steps](https://github.com/arq5x/lumpy-sv#pre-processing) to generate splitters and discordants, and then run lumpyexpress with the -S and -D flags.

**Comment by RobinvanVelzen** [comment]
Thanks for the clarifications. After doing the pre-processing steps with samtools lumpyexpress runs as expected!
