### ISSUE TITLE
Error removing element:11,134777027,134777558,- 11,134777653,134777569,-        1

### ISSUE THREAD

**Issue by galaxyrise** [arq5x/lumpy-sv#76]
Hello,

I just processed 85 individual samples using lumpy.  All completed successfully except one, which made it to Chr11 and then crashed with the following error:

Error removing element:11,134777027,134777558,- 11,134777653,134777569,-        1

I realize this isn't much to go on, but that is the extent of the error message and I'm afraid I can't share the source bams due to confidentiality issues.

Edit: Forgot to mention that I am using the latest version (v0.2.11) and lumpy  (not lumpyexress).  The problematic location in the error message is right near the end of Chr11.

**Comment by ryanlayer** [comment]
It is very likely that the cigar string for the offending alignment is
strange.  Can you pull out the reads around this region and look for
anything funny?

On Thu, Apr 30, 2015 at 4:54 PM, galaxyrise <notifications@github.com>
wrote:

> Hello,
>
> I just processed 85 individual samples using lumpy. All completed
> successfully except one, which made it to Chr11 and then crashed with the
> following error:
>
> Error removing element:11,134777027,134777558,- 11,134777653,134777569,- 1
>
> I realize this isn't much to go on, but that is the extent of the error
> message and I'm afraid I can't share the source bams due to confidentiality
> issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/76>.
>



-- 
Ryan Layer

**Comment by galaxyrise** [comment]
Sure.  will report back in a while.

**Comment by galaxyrise** [comment]
There are a lot of records in that neighborhood.  For records spanning 134776000-134777999, my splitters have the following CIGARs (with counts):

      2 102H49M
      2 107H44M
      1 109H42M
      1 115H36M
      1 120H31M
      2 13H55M83H
      2 18M56I1M
      1 31S120M
      1 33M56I1M61S
      1 35M56I1M59S
      1 36M56I1M58S
      1 38M113H
      2 38M56I1M56S
      2 44S92M
      1 46M56I1M48S
      1 51M56I1M43S
      1 53M56I1M41S
      1 54S97M
      1 56S95M
      1 58S93M
      2 59S92M
      1 62H9M1I67M12H
      1 63S88M
      1 64M56I1M30S
      1 68M83H
      1 72S79M
      1 73S78M
      1 74S77M
      1 77H74M
      1 79M1I9M62H
      1 7H58M86H
      1 82S69M
      1 83H68M
      1 83M1I9M58H
      1 84H67M
      2 86H50M
      1 89H62M
      1 90H51M10H
      1 90H61M
      1 91H60M
      1 92H59M
      1 92M59S
      3 94H57M
      1 95H56M
      2 96H55M
      1 96M55S

My discordants have the following CIGARs:
      1 115H36M
      1 123M28S
      1 12S139M
      1 136M15S
      1 138M1D13M
     22 151M
      1 24M1I7M2D119M
      1 31S120M
      1 38M113H
      1 38M1D113M
      1 43M8I100M
      1 48M8D103M
      1 56I1M
      1 56I7M
      1 56S95M
      1 59S92M
      1 5S74M8D72M
      1 63M8D88M
      1 77H74M
      1 7H58M86H
      1 7S20M1I5M1I18M8D99M
      1 7S83M1D61M
      1 83H68M
      1 84H67M
      1 90H51M10H
      1 92M59S
      1 95H56M
      2 96H55M
      1 96M55S

**Comment by galaxyrise** [comment]
Here are the sam files for the region of interest (gzipped without headers).

Thanks!

**Comment by ryanlayer** [comment]
The attachment didn't make it through.  Can you resend to my email directly
(gmail, ryan.layer)?

On Thu, Apr 30, 2015 at 5:36 PM, galaxyrise <notifications@github.com>
wrote:

> Here are the sam files for the region of interest (gzipped without
> headers).
>
> Thanks!
>
> On Thu, Apr 30, 2015 at 2:06 PM, Ryan Layer <notifications@github.com>
> wrote:
>
> > It is very likely that the cigar string for the offending alignment is
> > strange. Can you pull out the reads around this region and look for
> > anything funny?
> >
> > On Thu, Apr 30, 2015 at 4:54 PM, galaxyrise <notifications@github.com>
> > wrote:
> >
> > > Hello,
> > >
> > > I just processed 85 individual samples using lumpy. All completed
> > > successfully except one, which made it to Chr11 and then crashed with
> the
> > > following error:
> > >
> > > Error removing element:11,134777027,134777558,-
> 11,134777653,134777569,-
> > 1
> > >
> > > I realize this isn't much to go on, but that is the extent of the error
> > > message and I'm afraid I can't share the source bams due to
> > confidentiality
> > > issues.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/arq5x/lumpy-sv/issues/76>.
> > >
> >
> >
> >
> > --
> > Ryan Layer
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/arq5x/lumpy-sv/issues/76#issuecomment-97966371>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/76#issuecomment-97975736>.
>



-- 
Ryan Layer

**Comment by galaxyrise** [comment]
Done.
