### ISSUE TITLE
Resequencing capture and lumpy.

### ISSUE THREAD

**Issue by smilefreak** [arq5x/lumpy-sv#79]
HI,
I have run lumpy on a resequencing runs involving various candidate genes and regulatory regions from throughout the genome. 

I am wondering how to interpret the calls and whether they make sense. Most of the calls are supported by pair-end reads only, which I am skeptical of. But a few are supported by Split reads, which I can believe more. Does anyone have any experience of advice.

Thankyou for your time.
 James.

**Comment by ryanlayer** [comment]
What is your fragment length and read size?

On Mon, May 4, 2015 at 6:35 PM, James Boocock <notifications@github.com>
wrote:

> HI,
> I have run lumpy on a resequencing runs involving various candidate genes
> and regulatory regions from throughout the genome.
>
> I am wondering how to interpret the calls and whether they make sense.
> Most of the calls are supported by pair-end reads only, which I am
> skeptical of. But a few are supported by Split reads, which I can believe
> more. Does anyone have any experience of advice.
>
> Thankyou for your time.
> James.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/79>.
>



-- 
Ryan Layer

**Comment by smilefreak** [comment]
HI Ryan, 

Read length is 100bp, 
with insert size from a library depicted in the following plot from one sample taken from picard.

![test metrics](https://cloud.githubusercontent.com/assets/605678/7464201/ee3e9bf8-f314-11e4-82b8-b1473394649d.png)

**Comment by ryanlayer** [comment]
What was your lumpy command?

On Mon, May 4, 2015 at 6:53 PM, James Boocock <notifications@github.com>
wrote:

> HI Ryan,
>
> Read length is 100bp,
> with insert size from a library depicted in the following plot from one
> sample taken from picard.
>
> [image: test metrics]
> <https://cloud.githubusercontent.com/assets/605678/7464201/ee3e9bf8-f314-11e4-82b8-b1473394649d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/79#issuecomment-98879482>.
>



-- 
Ryan Layer

**Comment by smilefreak** [comment]
Hi,

Read length is 100bp.
Here is a plot of the insert size, the capture was done using a custom library. 
![test metrics](https://cloud.githubusercontent.com/assets/605678/7464425/312791a2-f317-11e4-8859-783006e14493.png)


The command was
```
lumpyexpress -o all.vcf -B <sample 1> -B <sample 2> etc.cc

```

Im also running it again in single sample mode and then svtyper and merging the calls using some of the scripts that are provided, but I don't have the data for that. 

Cheers James

**Comment by cc2qe** [comment]
We've been seeing reported issues with lumpyexpress without pre-extracted splitters and discordant reads, and for now we've discontinued support for this feature. You can try running lumpyexpress with the "-k" flag, and examine the temporary sample.splitters.bam file to ensure that it's being generated properly. If not, I'd suggest manually pre-extracting splitters and discordants using the commands here:
https://github.com/arq5x/lumpy-sv#pre-processing

**Comment by smilefreak** [comment]
Ahh, thanks for that, I am now getting considerably less CNVs. Far more reasonable :+1:
