### ISSUE TITLE
pysam

### ISSUE THREAD

**Issue by mxqian** [arq5x/lumpy-sv#80]
Which version of pysam should be used? And when I downloaded the tar.gz, the py files in script/bamkit were always missed. But I can find them on the web of github. Pls. check it. Thanks.

**Comment by mxqian** [comment]
Moreover, which version for numpy, samtools, and so on?

**Comment by cc2qe** [comment]
You'll need to run this command after downloading the tar.gz file to pull in recursive submodules
```
git submodule update --init
```

Also, added dependency version info to the README

**Comment by mxqian** [comment]
I just can see that "python 2.7 with pysam and numpy".  I have the errors:
> AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'is_supplementary'

> File "~/apps/lumpy-sv-0.2.11//scripts/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64

I have tested: pysam-0.7.8-py2.7-linux-x86_64, pysam-0.8.2.1-py2.7-linux-x86_64, pysam-0.8.3-py2.7-linux-x86_64. However, none of them can work and with a little bit different errors.
