### ISSUE TITLE
lumpy hurdles

### ISSUE THREAD

**Issue by calkan** [arq5x/lumpy-sv#84]
hi @ryanlayer @cc2qe  and @arq5x 

I'm using v 0.2.11.  I have one minor, and one major issue:

minor: for some reason lumpyexpress script was not able to call the unix tools like dirname, tr, etc. I had to add: 
export PATH=$PATH:/usr/bin:/bin

at the top of the script, then it worked. 

major:

here is the commandline:
lumpyexpress -B bunchofbams -S bunchofsplitters -D bunchofdiscordants -o output.vcf

it worked, generated the vcf, but GT's are ./.   is that normal? or should I just assume SU>=some_cutoff is 0/1 or 1/1 and SU<some_cutoff are 0/0?

**Comment by cc2qe** [comment]
Hey Can,

Actually that is the expected behavior for Lumpy. You can filter variants for quality by requiring SU>=threshold. To generate proper genotypes, try using [SVTyper](https://github.com/cc2qe/svtyper).

```
svtyper \
        -i lumpy.vcf \
        -B bam1.bam,bam2.bam \
        -S bam1.splitters.bam,bam2.splitters.bam \
        > output.vcf
```

It's still pretty slow for genotyping multiple BAMs but we are working to improve that.

**Comment by calkan** [comment]
Thanks Colby

**Comment by calkan** [comment]
errr.  the files are there, but:

IOError: file `NA12877/NA12877.recal.bam,NA12878/NA12878.recal.bam,NA12879/NA12879.recal.bam,NA12880/NA12880.recal.bam,NA12881/NA12881.recal.bam,NA12882/NA12882.recal.bam,NA12883/NA12883.recal.bam,NA12884/NA12884.recal.bam,NA12885/NA12885.recal.bam,NA12886/NA12886.recal.bam,NA12887/NA12887.recal.bam,NA12888/NA12888.recal.bam,NA12889/NA12889.recal.bam,NA12890/NA12890.recal.bam,NA12891/NA12891.recal.bam,NA12892/NA12892.recal.bam,NA12893/NA12893.recal.bam` not found

**Comment by cc2qe** [comment]
Ok, I'm not sure why that occurs but in any case, with 17 genomes you should probably run them in parallel.

For each sample, in parallel:
```
svtyper \
        -i lumpy.vcf \
        -B bam1.bam \
        -S bam1.splitters.bam \
        > output1.vcf
```
After they all finish:
```
cat lumpy.vcf \
        | svtyper/scripts/vcf_group_multiline.py \
        | svtyper/scripts/vcf_paste.py \
            -q \
            -m -
            output1.vcf output2.vcf output3.vcf output4.vcf \
        > final.vcf
```

This will be much faster and it is our current protocol, although we haven't released it officially yet.

**Comment by cc2qe** [comment]
the scripts above can be found here: https://github.com/cc2qe/svtyper/tree/master/scripts
