### ISSUE TITLE
Lumpy on BWA aln data

### ISSUE THREAD

**Issue by jwalabroad** [arq5x/lumpy-sv#89]
Hi Ryan,

We would like to run Lumpy on a large set of BWA aln aligned tumor/normal BAM files. I am wondering how import it is to have ran BWA-MEM over BWA aln on this original data. Realigning multiple terabytes of BAM files is something we would rather avoid :)

-Jeremiah

**Comment by arq5x** [comment]
Hi Jeremiah,

The main issue with bwa aln is that unlike BWA-MEM, it does not create "split" alignments at sites of SV breakpoints.  Consequently, I think you would be limited to using LUMPY for SV detection with solely discordant, paired-end alignments. This would limit sensitivity.  

@ryanlayer and @cc2qe - am I forgetting any tricks that could be applied to bwa aln BAMs to recover split alignments?

**Comment by ryanlayer** [comment]
You can scan the bam and extract any soft clip reads into a a new FASTQ file, then realign those with BWA MEM.

**Comment by jwalabroad** [comment]
Thanks Ryan and Aaron for the help. I ended up re-visiting this and decided to re-align using BWA-MEM.
