### ISSUE TITLE
-e  Show evidence for each call

### ISSUE THREAD

**Issue by MinocheAE** [arq5x/lumpy-sv#91]
Hi,
is there a way to output the supporting split reads and paired reads for each call e.g. in bed format?
I would have expected that "-e" is doing this, but I do not get any additional file, nor does the vcf file contain any additional lines.

This is my command: lumpy -e -mw 4 -tt 0 -msw 2 -x exclude.bed -pe  .. -sr  ..  > out.vcf

Thanks

**Comment by ryanlayer** [comment]
Try adding the "-b" option to bedpe instead of VCF.

On Wed, Jul 8, 2015 at 3:39 AM, MinocheAE <notifications@github.com> wrote:

> Hi,
> is there a way to output the supporting split reads and paired reads for
> each call e.g. in bed format?
> I would have expected that "-e" is doing this, but I do not get any
> additional file, nor does the vcf file contain any additional lines.
>
> This is my command: lumpy -e -mw 4 -tt 0 -msw 2 -x exclude.bed -pe .. -sr
> .. > out.vcf
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/91>.
>



-- 
Ryan Layer
