### ISSUE TITLE
Genotyping of Lumpy results

### ISSUE THREAD

**Issue by holtgrewe** [arq5x/lumpy-sv#92]
Hi, could you document somewhere in some more detail how to use the temporary split read files for genotyping Lumpy results with svtyper in case of using more than one input BAM file?

**Comment by cc2qe** [comment]
In the command line help, it says:
```
  -B BAM, --bam BAM     BAM file(s), comma-separated if genotyping multiple BAMs
  -S SPLIT_BAM, --split_bam SPLIT_BAM
                        split-read bam file for sample, comma-separated if genotyping multiple BAMs
```

The piece of information that is missing is that these need to be in one-to-one correspondence between the -B and -S lists, so if `-B seq1.bam,seq2.bam`, the splitters should be `-S seq1.splitters.bam,seq2.splitters.bam`. SVTyper will automatically determine the sample names from the SM field of the readgroup. Will update documentation with these details.
