### ISSUE TITLE
Error removing element

### ISSUE THREAD

**Issue by boboppie** [arq5x/lumpy-sv#93]
Dear @ryanlayer ,

We have Illumina's latest 150bp ISSAC aligned bams in house, and when I ran Lumpy on one of our samples I got:

```
Running LUMPY...

/modules/out/modulebin/lumpy/0.2.11/bin/lumpy  \
    -t lumpytest.vcf.E7ASxG8VfyiN/lumpytest.vcf \
    -msw 4 \
    -tt 0 \
     \
     -pe bam_file:lumpytest.discordants.bam,histo_file:lumpytest.vcf.E7ASxG8VfyiN/lumpytest.vcf.sample1.lib1.x4.histo,mean:491.117962812,stdev:121.570806859,read_length:150,min_non_overlap:150,discordant_z:5,back
_distance:10,weight:1,id:LP2000803-DNA_A01,min_mapping_threshold:20,read_group:0 \
     -sr bam_file:lumpytest.splitters.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:LP2000803-DNA_A01,min_clip:20 \
    > lumpytest.vcf
1       1000000
2       1000000
3       1000000
4       1000000
5       1000000
6       1000000
7       1000000
Error removing element:7,786163,786990,-        7,787949,787817,+       1
/modulebin/lumpy/0.2.11/bin/lumpyexpress: line 411: 66992 Aborted                 $LUMPY $PROB_CURVE -t ${TEMP_DIR}/${OUTBASE} -msw $MIN_SAMPLE_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $OUTPUT
```

I was using lumpyexpress:

```
lumpyexpress -B lumpytest.bam  -o lumpytest.vcf -v
```

Can I send you a slice of bam around that region please?

Best wishes,
Fengyuan

**Comment by boboppie** [comment]
I've created a slice by

```
samtools view -b lumpytest.bam 7:780000-790000 > slice.bam
```

Here - https://www.dropbox.com/s/lswvla0q84z36ts/slice.bam?dl=0

Thanks in advance!

Fengyuan

**Comment by ryanlayer** [comment]
Can you also upload your histo file?

On Fri, Aug 14, 2015 at 5:43 AM, Fengyuan Hu <notifications@github.com>
wrote:

> I've created a slice by
>
> samtools view -b lumpytest.bam 7:780000-790000 > slice.bam
>
> Here - https://www.dropbox.com/s/lswvla0q84z36ts/slice.bam?dl=0
>
> Thanks in advance!
>
> Fengyuan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/93#issuecomment-131084717>.
>



-- 
Ryan Layer

**Comment by boboppie** [comment]
Hi @ryanlayer ,

Sorry for slow reply, here is the histo - https://www.dropbox.com/s/k78mmosp9lkahfz/lumpytest.rg0.histo?dl=0

It is created by:
```bash
samtools view -r 0 lumpytest.bam | tail -n+100000  | $lumpy_HOME/scripts/pairend_distro.py -r 101 -X 4 -N 10000 -o lumpytest.rg0.histo
```

**Comment by ryanlayer** [comment]
Can you pull the latest version and see if it is now fixed?

On Tue, Sep 8, 2015 at 3:19 AM, Fengyuan Hu <notifications@github.com>
wrote:

> Hi @ryanlayer <https://github.com/ryanlayer> ,
>
> Sorry for slow reply, here is the histo -
> https://www.dropbox.com/s/k78mmosp9lkahfz/lumpytest.rg0.histo?dl=0
>
> It is created by:
>
> samtools view -r 0 lumpytest.bam | tail -n+100000  | $lumpy_HOME/scripts/pairend_distro.py -r 101 -X 4 -N 10000 -o lumpytest.rg0.histo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/93#issuecomment-138492643>.
>



-- 
Ryan Layer

**Comment by boboppie** [comment]
Thanks for the quick fix, it works now! Could explain how you fix it?

**Comment by ryanlayer** [comment]
Some pairs can have complex CIGAR strings that include only a few matches
and result in very small read lengths.  I made the error checking robust to
these reads.

On Tue, Sep 8, 2015 at 3:32 PM, Fengyuan Hu <notifications@github.com>
wrote:

> Thanks for the quick fix, it works now! Could explain how you fix it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/93#issuecomment-138708615>.
>



-- 
Ryan Layer

**Comment by boboppie** [comment]
Thank you @ryanlayer !
