### ISSUE TITLE
LUMPY output

### ISSUE THREAD

**Issue by Bazinga199122** [arq5x/lumpy-sv#95]
Are all the SVs that LUMPY called at single base resolution?What does the "IMPRECISE" flag mean?

**Comment by ryanlayer** [comment]
Lumpy gives two probabilistic intervals for every call.  The point given in
2nd column of the VCF and the "END" value in the INFO field correspond to
the points in the intervals with the highest probability.  The CIPOS and
CIEND give the down/up stream positions of the intervals and CIPOS95 and
CIEND95 give the 95% confidence interval.

On Fri, Aug 28, 2015 at 9:39 AM, Bazinga199122 <notifications@github.com>
wrote:

> Are all the SVs that LUMPY called at single base resolution?What does the
> "IMPRECISE" flag mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/95>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
So,basically,I cannot treat the 2nd column and "END" value as the exact breakpoint,right?

**Comment by cc2qe** [comment]
you can do the following to extract the breakpoints in which 95% of the probbility distribution for both breakends is at a single base:

cat lumpy.vcf | vawk '! I$IMPRECISE'

**Comment by Bazinga199122** [comment]
Thanks for your reply!
