### ISSUE TITLE
lumpy with bwa sampe

### ISSUE THREAD

**Issue by Bazinga199122** [arq5x/lumpy-sv#97]
Hi,

Is lumpy compatible with bwa sampe output? or just work file with bwa mem? 
I provide bwa sampe aligned bam to extractSplitReads_BwaMem and get nothing.
Thanks in advance!

**Comment by ryanlayer** [comment]
Hi, can you please post this to the group at
https://groups.google.com/forum/#!forum/lumpy-discuss

On Tue, Sep 22, 2015 at 8:59 AM, Bazinga199122 <notifications@github.com>
wrote:

> Hi,
>
> Is lumpy compatible with bwa sampe output? or just work file with bwa mem?
> I provide bwa sampe aligned bam to extractSplitReads_BwaMem and get
> nothing.
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
Sorry, in China mainland,google is blocked.

**Comment by ryanlayer** [comment]
In short, bwa sampe does not do split read alignment.   If you cannot
realign, then try "split_unmapped_to_fasta.pl" to extract candidate split
reads from your aligned files, then use a split read aligner (I like YAHA
http://www.ncbi.nlm.nih.gov/pubmed/?term=22829624,
https://github.com/GregoryFaust/yaha) to get your splitters.

On Tue, Sep 22, 2015 at 9:23 AM, Bazinga199122 <notifications@github.com>
wrote:

> Sorry, in China mainland,google is blocked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142322801>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
Thanks for your reply

**Comment by Bazinga199122** [comment]
I noticed that older version of lumpy could be compatible with bwa aln. Right?

**Comment by ryanlayer** [comment]
You would need to bwa sampe the result of bwa aln

On Tue, Sep 22, 2015 at 9:40 AM, Bazinga199122 <notifications@github.com>
wrote:

> I noticed that older version of lumpy could be compatible with bwa aln.
> Right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142327700>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
Right!

**Comment by Bazinga199122** [comment]
And which version of lumpy do you recommend ?

**Comment by ryanlayer** [comment]
Get the latest from github:

git clone --recursive https://github.com/arq5x/lumpy-sv.git
cd lumpy-sv
make


On Tue, Sep 22, 2015 at 9:55 AM, Bazinga199122 <notifications@github.com>
wrote:

> And which version of lumpy do you recommend ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142331967>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
Hi, I tried lumpy with bwa sampe out as you suggested. In short, bwa aligned bam serves as discordants.bam and YAHA aligned bam servers as splitters.bam.However, in the output vcf file I got many SVs than expected.Any suggestions?

**Comment by ryanlayer** [comment]
What command did you run?

On Wed, Sep 23, 2015 at 10:12 AM, Bazinga199122 <notifications@github.com>
wrote:

> Hi, I tried lumpy with bwa sampe out as you suggested. In short, bwa
> aligned bam serves as discordants.bam and YAHA aligned bam servers as
> splitters.bam.However, in the output vcf file I got many SVs than
> expected.Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142650794>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
bwa aln +sampe > sorted.bam
split_unmapped_to_fasta.pl sorted.bam >sample.um.fq
yaha sample.um.fq > sample.sr.bam
lumpy -sr sample.sr.bam -pe sorted.bam > final.vcf

**Comment by ryanlayer** [comment]
Can you give me the exact commands as you ran them?

On Wed, Sep 23, 2015 at 10:32 AM, Bazinga199122 <notifications@github.com>
wrote:

> bwa aln +sampe > sorted.bam
> split_unmapped_to_fasta.pl sorted.bam >sample.um.fq
> yaha sample.um.fq > sample.sr.bam
> lumpy -sr sample.sr.bam -pe sorted.bam > final.vcf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142655540>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
ok
# bwa aln+sample:
bwa aln dmel-all-chromosome-r6.03.fasta RAL_208_1.fastq > RAL_208_1.sai
bwa aln dmel-all-chromosome-r6.03.fasta RAL_208_2.fastq > RAL_208_2.sai
bwa sampe -r "@RG\tID:RAL_208\tPL:illumina\tPU:illumina\tLB:RAL_208\tSM:RAL_208\"  
dmel-all-chromosome-r6.03.fasta RAL_208_1.sai RAL_208_2.sai RAL_208_1.fastq RAL_208_2.fastq |samtools view -b -S > RAL_208.bam
samtools sort RAL_208.bam RAL_208.sorted

split_unmapped_to_fasta.pl RAL_208.sorted.bam >sample.um.fq

# YAHA realign
yaha -g dmel-all-chromosome-r6.03.fasta -L 11
yaha -x dmel-all-chromosome-r6.03.X11_01_65525S -q sample.um.fq -osh stdout -M 15 -H 2000 -L 11 |samtools view -Sb - > sample.sr.bam
samtools sort sample.sr.bam sample.sr.sorted

# run lumpy
samtools view RAL_208.sorted.bam | tail -n+100000 | pairend_distro.py -r 75 -X 4 -N 100000  -o RAL_208.histo
lumpy -mw 2 -tt 0  -pe id:RAL_208,bam_file:RAL_208.sorted.bam,read_group:"@RG\tID:RAL_208\tPL:illumina\tPU:illumina\tLB:RAL_208\tSM:RAL_208",histo_file:RAL_208.histo,mean:185,stdev:24,read_length:75,min_non_overlap:75,discordant_z:5,back_distance:10,weight:1,min_mapping_threshold:20 -sr id:RAL_208,bam_file:sample.sr.sorted.bam,back_distance:10,weight:1,min_mapping_threshold:20 > RAL_208.vcf

**Comment by ryanlayer** [comment]
Your min weight is 2, which is pretty low.  What is the coverage?

On Wed, Sep 23, 2015 at 11:00 AM, Bazinga199122 <notifications@github.com>
wrote:

> ok
> bwa aln+sample:
>
> bwa aln dmel-all-chromosome-r6.03.fasta RAL_208_1.fastq > RAL_208_1.sai
> bwa aln dmel-all-chromosome-r6.03.fasta RAL_208_2.fastq > RAL_208_2.sai
> bwa sampe -r "@RG <https://github.com/RG>
> \tID:RAL_208\tPL:illumina\tPU:illumina\tLB:RAL_208\tSM:RAL_208\"
>
> dmel-all-chromosome-r6.03.fasta RAL_208_1.sai RAL_208_2.sai
> RAL_208_1.fastq RAL_208_2.fastq |samtools view -b -S > RAL_208.bam
> samtools sort RAL_208.bam RAL_208.sorted
>
> split_unmapped_to_fasta.pl RAL_208.sorted.bam >sample.um.fq
> YAHA realign
>
> yaha -g dmel-all-chromosome-r6.03.fasta -L 11
> yaha -x dmel-all-chromosome-r6.03.X11_01_65525S -q sample.um.fq -osh
> stdout -M 15 -H 2000 -L 11 |samtools view -Sb - > sample.sr.bam
> samtools sort sample.sr.bam sample.sr.sorted
> run lumpy
>
> samtools view RAL_208.sorted.bam | tail -n+100000 | pairend_distro.py -r
> 75 -X 4 -N 100000 -o RAL_208.histo
> lumpy -mw 2 -tt 0 -pe id:RAL_208,bam_file:RAL_208.sorted.bam,read_group:"
> @RG <https://github.com/RG>\tID:RAL_208\tPL:illumina\tPU:illumina\tLB:RAL_208\tSM:RAL_208",histo_file:RAL_208.histo,mean:185,stdev:24,read_length:75,min_non_overlap:75,discordant_z:5,back_distance:10,weight:1,min_mapping_threshold:20
> -sr
> id:RAL_208,bam_file:sample.sr.sorted.bam,back_distance:10,weight:1,min_mapping_threshold:20
> > RAL_208.vcf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142663036>.
>



-- 
Ryan Layer

**Comment by Bazinga199122** [comment]
25X,when set to 4,I still get much more SVs than expected.

**Comment by ryanlayer** [comment]
Try using an exclude file.  Heng Li's low complexity regions are a good
start: https://github.com/lh3/varcmp/tree/master/scripts/

On Wed, Sep 23, 2015 at 11:05 AM, Bazinga199122 <notifications@github.com>
wrote:

> 25X,when set to 4,I still get much more SVs than expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/97#issuecomment-142664739>.
>



-- 
Ryan Layer
