### ISSUE TITLE
Error removing reads 

### ISSUE THREAD

**Issue by fred3ric** [arq5x/lumpy-sv#99]
Hi Ryan, 

We updated the last version of Lumpy (v.0.2.11) and got the same issue as https://github.com/arq5x/lumpy-sv/issues/94.
Here the error output:
Error removing element:10,1369960,1369950,+ 10,1369981,1369971,-    1
I send you an email with a link to download the slice bam file containing the offending region and the histo file.

Thanks for your help,
Frederic

**Comment by ryanlayer** [comment]
Can you also reply with your exact command?  Thanks.
